### ISSUE TITLE
installation issue - grpcio, guiding_centres

### ISSUE THREAD

**Issue by LLLiPhys** [wannier-berri/wannier-berri#102]
Dear Community,

I came across a problem when using "pip install wannierberri" to install the latest version of wannierberri. The error message is shown as below:

Command "/anaconda/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-bgl863v_/grpcio/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-t8bckwjj/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-bgl863v_/grpcio/

As far as I learned from the installation guide (https://wannier-berri.org/install.html), the dependencies are quite basic and will be installed automatically. I am using anaconda python.

Can you help to figure out this installation problem ? Thank you.

Best regards,
Longlong Li

**Comment by stepan-tsirkin** [comment]
@LLLiPhys , the dependencies are not that basic, as they used to be when that line was written. 

Clearly, there is a problem installing the `grpcio` package, which is required by `ray` .  Please, provide more info on your setup, like Operating system, version of python, etc..

Here they say there used to be a problem with `setuptools`: https://github.com/grpc/grpc/issues/24037
also read here: https://stackoverflow.com/questions/56357794/unable-to-install-grpcio-using-pip-install-grpcio
try upgrading/downgrading  `setuptools`, `pip` or try to install different versions of `grpcio`  .  

Looks like some conflict of other packages versions, but I cannot say more, I did not encounter such problem.

Please report on the results.

**Comment by LLLiPhys** [comment]
@stepan-tsirkin , the operating system is CentOS 7 and the version of python is 3.6.5.

Following the link as you mentioned, first install `grpcio` and then install `wannierberri`, the problem is gone. Thank you for this solution.

**Comment by stepan-tsirkin** [comment]
Great, 
@LLLiPhys , note that 3.6.5 is rather old, the latest of 3.6  family is [3.6.15](https://www.python.org/downloads/release/python-3615/), and even that will loose support soon.

So far, we test `wannierberri` with opython `3.6.15`, `3.7.12` and `3.8.12` , but may drop support of 3.6 in the future. 

So consider upgrading python.

**Comment by LLLiPhys** [comment]
@stepan-tsirkin , thanks for this suggestion. Surely I will update python. At moment it seems working with the latest wannierberri.

I have `wannier90.eig`, `wannier90.mmn`, and `wannier90.chk` at hand. Previously I calculated optical conductivity using wannierberri-v0.9.2.2 and this version worked pretty fine. But running the same calculation with wannierberri-v0.11.0 did not work well and terminated with the following error:

using fortio to read
Reading restart information from file wannier90.chk :
Time to read .chk : 0.045194387435913086
Time for MMN.__init__() : 0.4520742893218994 , read : 0.44083690643310547 , headstring 0.011237382888793945
Traceback (most recent call last):
  File "run_berri.py", line 43, in <module>
    main()    
  File "run_berri.py", line 40, in main
    calc(efermi=0.0, nkpts=10, tempt=10, broad=0.01, nprocs=4)
  File "run_berri.py", line 14, in calc
    system = wberri.System_w90("wannier90", berry=True)
  File "/anaconda/envs/wb/lib/python3.6/site-packages/wannierberri/__system_w90.py", line 99, in __init__
    wannier_centers_cart_new,self.wannier_centers_cart_auto-wannier_centers_cart_new))
AssertionError: the difference between read
[[-9.7641e-07  1.8400e+00  1.1562e+01]
 [-3.7005e-06  1.8400e+00  1.1562e+01]
 [-2.2105e-05  1.8112e+00  1.1564e+01]
 [-5.1979e-06  1.8113e+00  1.1564e+01]
 [-1.4966e-06  1.8700e+00  1.1564e+01]
 [-2.3164e-06  1.8699e+00  1.1564e+01]
 [-1.9675e-06  1.7519e+00  1.1563e+01]
 [-1.8201e-06  1.7519e+00  1.1563e+01]
 [-5.3912e-07  1.9247e+00  1.1563e+01]
 [-2.5529e-06  1.9247e+00  1.1563e+01]
 [ 1.5939e+00  9.2082e-01  1.7784e+01]
 [ 1.5939e+00  9.2081e-01  1.7784e+01]
 [ 1.5940e+00  9.5015e-01  1.7784e+01]
 [ 1.5940e+00  9.5014e-01  1.7784e+01]
 [ 1.5939e+00  8.9012e-01  1.7784e+01]
 [ 1.5939e+00  8.9032e-01  1.7784e+01]
 [ 1.5939e+00  1.0088e+00  1.7783e+01]
 [ 1.5939e+00  1.0088e+00  1.7783e+01]
 [ 1.5939e+00  8.3611e-01  1.7783e+01]
 [ 1.5939e+00  8.3611e-01  1.7783e+01]
 [ 4.1658e-06  1.8406e+00  1.6148e+01]
 [ 8.2677e-06  1.8406e+00  1.6148e+01]
 [-1.6404e-06  1.8285e+00  1.6288e+01]
 [-2.1198e-07  1.8285e+00  1.6288e+01]
 [-5.5333e-06  1.8502e+00  1.6286e+01]
 [ 1.5596e-06  1.8503e+00  1.6286e+01]
 [ 1.5939e+00  9.2023e-01  9.9116e+00]
 [ 1.5939e+00  9.2023e-01  9.9116e+00]
 [ 1.5939e+00  9.3418e-01  1.0073e+01]
 [ 1.5939e+00  9.3421e-01  1.0073e+01]
 [ 1.5939e+00  9.0867e-01  1.0071e+01]
 [ 1.5939e+00  9.0865e-01  1.0071e+01]
 [ 1.5939e+00  9.2014e-01  1.3200e+01]
 [ 1.5939e+00  9.2015e-01  1.3200e+01]
 [ 1.5939e+00  9.3268e-01  1.3059e+01]
 [ 1.5939e+00  9.3269e-01  1.3059e+01]
 [ 1.5939e+00  9.1014e-01  1.3061e+01]
 [ 1.5939e+00  9.1013e-01  1.3061e+01]
 [ 4.7034e-06  1.8406e+00  1.9439e+01]
 [ 1.5647e-06  1.8406e+00  1.9439e+01]
 [-3.7195e-06  1.8268e+00  1.9274e+01]
 [ 2.1676e-06  1.8268e+00  1.9274e+01]
 [ 4.1416e-06  1.8519e+00  1.9276e+01]
 [ 7.0512e-06  1.8519e+00  1.9276e+01]]
 and evluated 
[[-9.7641e-07+0.j  1.8400e+00+0.j  1.1562e+01+0.j]
 [-3.7005e-06+0.j  1.8400e+00+0.j  1.1562e+01+0.j]
 [-2.2105e-05+0.j  1.8112e+00+0.j  1.1564e+01+0.j]
 [-5.1979e-06+0.j  1.8113e+00+0.j  1.1564e+01+0.j]
 [-1.4966e-06+0.j  1.8700e+00+0.j  1.1564e+01+0.j]
 [-2.3164e-06+0.j  1.8699e+00+0.j  1.1564e+01+0.j]
 [-1.9675e-06+0.j  1.7519e+00+0.j  1.1563e+01+0.j]
 [-1.8201e-06+0.j  1.7519e+00+0.j  1.1563e+01+0.j]
 [-5.3912e-07+0.j  1.9247e+00+0.j  1.1563e+01+0.j]
 [-2.5529e-06+0.j  1.9247e+00+0.j  1.1563e+01+0.j]
 [ 1.5939e+00+0.j  9.2082e-01+0.j -1.1560e+01+0.j]
 [ 1.5939e+00+0.j  9.2081e-01+0.j -1.1560e+01+0.j]
 [ 1.5940e+00+0.j  9.5015e-01+0.j -1.1561e+01+0.j]
 [ 1.5940e+00+0.j  9.5014e-01+0.j -1.1561e+01+0.j]
 [ 1.5939e+00+0.j  8.9012e-01+0.j -1.1561e+01+0.j]
 [ 1.5939e+00+0.j  8.9032e-01+0.j -1.1561e+01+0.j]
 [ 1.5939e+00+0.j  1.0088e+00+0.j -1.1562e+01+0.j]
 [ 1.5939e+00+0.j  1.0088e+00+0.j -1.1562e+01+0.j]
 [ 1.5939e+00+0.j  8.3611e-01+0.j -1.1562e+01+0.j]
 [ 1.5939e+00+0.j  8.3611e-01+0.j -1.1562e+01+0.j]
 [ 4.1658e-06+0.j  1.8406e+00+0.j -1.3197e+01+0.j]
 [ 8.2677e-06+0.j  1.8406e+00+0.j -1.3197e+01+0.j]
 [-1.6404e-06+0.j  1.8285e+00+0.j -1.3057e+01+0.j]
 [-2.1198e-07+0.j  1.8285e+00+0.j -1.3057e+01+0.j]
 [-5.5333e-06+0.j  1.8502e+00+0.j -1.3059e+01+0.j]
 [ 1.5596e-06+0.j  1.8503e+00+0.j -1.3059e+01+0.j]
 [ 1.5939e+00+0.j  9.2023e-01+0.j  9.9116e+00+0.j]
 [ 1.5939e+00+0.j  9.2023e-01+0.j  9.9116e+00+0.j]
 [ 1.5939e+00+0.j  9.3418e-01+0.j  1.0073e+01+0.j]
 [ 1.5939e+00+0.j  9.3421e-01+0.j  1.0073e+01+0.j]
 [ 1.5939e+00+0.j  9.0867e-01+0.j  1.0071e+01+0.j]
 [ 1.5939e+00+0.j  9.0865e-01+0.j  1.0071e+01+0.j]
 [ 1.5939e+00+0.j  9.2014e-01+0.j  1.3200e+01+0.j]
 [ 1.5939e+00+0.j  9.2015e-01+0.j  1.3200e+01+0.j]
 [ 1.5939e+00+0.j  9.3268e-01+0.j  1.3059e+01+0.j]
 [ 1.5939e+00+0.j  9.3269e-01+0.j  1.3059e+01+0.j]
 [ 1.5939e+00+0.j  9.1014e-01+0.j  1.3061e+01+0.j]
 [ 1.5939e+00+0.j  9.1013e-01+0.j  1.3061e+01+0.j]
 [ 4.7034e-06+0.j  1.8406e+00+0.j -9.9053e+00+0.j]
 [ 1.5647e-06+0.j  1.8406e+00+0.j -9.9053e+00+0.j]
 [-3.7195e-06+0.j  1.8268e+00+0.j -1.0070e+01+0.j]
 [ 2.1676e-06+0.j  1.8268e+00+0.j -1.0070e+01+0.j]
 [ 4.1416e-06+0.j  1.8519e+00+0.j -1.0068e+01+0.j]
 [ 7.0512e-06+0.j  1.8519e+00+0.j -1.0068e+01+0.j]]
 wannier centers is 
[[-3.0840e-17+0.j -7.3590e-12+0.j  0.0000e+00+0.j]
 [-2.6214e-17+0.j -7.3594e-12+0.j  1.7764e-15+0.j]
 [ 4.0088e-17+0.j -7.2360e-12+0.j  0.0000e+00+0.j]
 [-1.1565e-17+0.j -7.2360e-12+0.j  1.7764e-15+0.j]
 [-4.7801e-17+0.j -7.4893e-12+0.j  1.7764e-15+0.j]
 [ 5.3964e-18+0.j -7.4898e-12+0.j  1.7764e-15+0.j]
 [ 3.3923e-17+0.j -7.0342e-12+0.j  1.7764e-15+0.j]
 [ 1.8504e-17+0.j -7.0339e-12+0.j  3.5527e-15+0.j]
 [-4.0091e-17+0.j -7.6763e-12+0.j -1.7764e-15+0.j]
 [-2.7756e-17+0.j -7.6770e-12+0.j  0.0000e+00+0.j]
 [-6.3765e-12+0.j -3.6843e-12+0.j  2.9344e+01+0.j]
 [-6.3762e-12+0.j -3.6843e-12+0.j  2.9344e+01+0.j]
 [-6.3760e-12+0.j -3.8094e-12+0.j  2.9344e+01+0.j]
 [-6.3760e-12+0.j -3.8093e-12+0.j  2.9344e+01+0.j]
 [-6.3760e-12+0.j -3.5517e-12+0.j  2.9344e+01+0.j]
 [-6.3753e-12+0.j -3.5522e-12+0.j  2.9344e+01+0.j]
 [-6.3765e-12+0.j -4.0090e-12+0.j  2.9344e+01+0.j]
 [-6.3762e-12+0.j -4.0092e-12+0.j  2.9344e+01+0.j]
 [-6.3760e-12+0.j -3.3670e-12+0.j  2.9344e+01+0.j]
 [-6.3760e-12+0.j -3.3672e-12+0.j  2.9344e+01+0.j]
 [-9.2521e-18+0.j -7.3623e-12+0.j  2.9344e+01+0.j]
 [-2.1587e-17+0.j -7.3623e-12+0.j  2.9344e+01+0.j]
 [-4.4717e-17+0.j -7.3308e-12+0.j  2.9344e+01+0.j]
 [-1.5420e-17+0.j -7.3306e-12+0.j  2.9344e+01+0.j]
 [ 3.0839e-17+0.j -7.3868e-12+0.j  2.9344e+01+0.j]
 [ 2.1176e-22+0.j -7.3863e-12+0.j  2.9344e+01+0.j]
 [-6.3760e-12+0.j -3.6814e-12+0.j -1.7764e-15+0.j]
 [-6.3762e-12+0.j -3.6811e-12+0.j  1.7764e-15+0.j]
 [-6.3762e-12+0.j -3.7175e-12+0.j -1.7764e-15+0.j]
 [-6.3762e-12+0.j -3.7179e-12+0.j  1.7764e-15+0.j]
 [-6.3762e-12+0.j -3.6525e-12+0.j  1.7764e-15+0.j]
 [-6.3762e-12+0.j -3.6525e-12+0.j  0.0000e+00+0.j]
 [-6.3762e-12+0.j -3.6809e-12+0.j -1.7764e-15+0.j]
 [-6.3762e-12+0.j -3.6809e-12+0.j -3.5527e-15+0.j]
 [-6.3762e-12+0.j -3.7139e-12+0.j  0.0000e+00+0.j]
 [-6.3760e-12+0.j -3.7139e-12+0.j  0.0000e+00+0.j]
 [-6.3762e-12+0.j -3.6560e-12+0.j -1.7764e-15+0.j]
 [-6.3758e-12+0.j -3.6560e-12+0.j  1.7764e-15+0.j]
 [-4.6259e-17+0.j -7.3623e-12+0.j  2.9344e+01+0.j]
 [-2.0046e-17+0.j -7.3623e-12+0.j  2.9344e+01+0.j]
 [-4.0091e-17+0.j -7.3270e-12+0.j  2.9344e+01+0.j]
 [-4.7801e-17+0.j -7.3272e-12+0.j  2.9344e+01+0.j]
 [-2.9298e-17+0.j -7.3905e-12+0.j  2.9344e+01+0.j]
 [-3.8549e-17+0.j -7.3908e-12+0.j  2.9344e+01+0.j]]

Could you indicate me if you also need `wannier.chk`, `wannier90.eig`,  `wannier90.mmn`, and running scripts ?

**Comment by stepan-tsirkin** [comment]
By chance, didn't you use 'guiding_centres =  True' in Wannier90 ?  May it be related to #93 ?

**Comment by LLLiPhys** [comment]
Yes I used `guiding_centres = true` in wannier90.win. Also I used `spinor = true` to account for SOC.

**Comment by LLLiPhys** [comment]
@stepan-tsirkin , I just took a look at #93. In my case where a 2D material layer is placed at the center of the supercell, setting `guiding_centres = true` might be important, as also claimed there:
> (In most cases, guiding_centers does nothing, so the current implementation works. But there are some edge cases, like >monolayers placed at the center of the supercell, that guiding_centers have significant effects. I attached an example.)

**Comment by LLLiPhys** [comment]
@stepan-tsirkin , actually there was no particular reason to place the layer in the center of the unit cell, just my preference. But I will try what you mentioned - put the layer in the origin of the unit cell and let you know ASAP.

**Comment by stepan-tsirkin** [comment]
thanks, we are working on the issue (#93 , #108) to fix it in general.

**Comment by LLLiPhys** [comment]
That sounds very great, :-)

**Comment by jaemolihm** [comment]
This is fixed in #108 . You can add `guiding_centers = True` to the call of System_W90 (note that it is "centers", not "centres" as in Wannier90 😄 ) and that will overwrite the centers with those calculated by Wannier90.
