### ISSUE TITLE
Intrinsic anomalous Hall conductivity

### ISSUE THREAD

**Issue by shahramyalameha** [wannier-berri/wannier-berri#105]
Dear developers,
In the * -ahc_iter - * .dat file, which is related to the anomalous Hall conductivity tensor.
What do you mean by x, y, z (columns 2-4) and x, y, z (columns 5-7) in this file? How can the ahc_{xy} or ahc_{xx} be extracted from this data?

thank you,
Shahram

`    Efermi                                 x                  y                             z                               x                            y                             z      `

` -1.000000e+00          -6.265446e-17       2.198631e-15       1.606705e-15       8.156011e-17       2.150713e-15       1.548963e-15`
.....

**Comment by LLLiPhys** [comment]
@shahramyalameha , Hi, in terms of the definition of ahc_{ij}^k, the column with the name 'z' should be the one that you were looking for. It's better to convince this with the main developer @stepan-tsirkin.

**Comment by LLLiPhys** [comment]
BTW, there are two sets of x,y,z data. Is the 2nd set a repetition of the 1st one or are they different ?

**Comment by stepan-tsirkin** [comment]
exactly, the anomalous Hall conductivity is  an antisymmetric tensor sigma_ab, whci hcan be packed as a pseudovector sigma_c.  so 
sigma_ab  = epsilon_abc*sigma_c , where epsilon_abc is the Levi-Civita symbol. 

"xx" is zero, "xy" is "z", "xz" is "-y" , etc

**Comment by shahramyalameha** [comment]
Thank you for your reply.
