### ISSUE TITLE
Non-existent reference to `wanniertools` tutorials.

### ISSUE THREAD

**Issue by hongyi-zhao** [wannier-berri/wannier-berri#117]
[Here](http://wannier-berri.org/exampleFe.html) says the following: Also a nicely illustrated tutorial is published on the [WanierToools](https://www.wanniertools.org/tutorials/high-quality-wfs/) website. But currently, the official WanierToools website has been changed to [here](http://www.wanniertools.com/), and even so, the following webpage also doesn't exist:  https://www.wanniertools.com/tutorials/high-quality-wfs/.

Regards,
HZ

**Comment by stepan-tsirkin** [comment]
I am not sure which of the websites is newer, but I think the .org appeared after the .com . In any case, the provided link is valid, I just checked that it opens.

**Comment by hongyi-zhao** [comment]
Thank you for your comment. It seems that you are right. I want to add the following supplementary information: The [DOCUMENTATION](https://www.wanniertools.org/) pointed to http://www.wanniertools.com/.
