### ISSUE TITLE
Why does this project use workflows based on `.ci` and `.github` at the same time?

### ISSUE THREAD

**Issue by hongyi-zhao** [wannier-berri/wannier-berri#118]
Under the root directory of this project, I noticed the following directories: [.ci](https://github.com/wannier-berri/wannier-berri/tree/master/.ci) and [.github](https://github.com/wannier-berri/wannier-berri/tree/master/.github). According to my understanding, these are two similar workflows which can be used to the same job. So, Why does this project use workflows based on `.ci` and `.github` at the same time?

Regards,
HZ

**Comment by jaemolihm** [comment]
Thanks for pointing it out. We only use GitHub Actions for CI. The folder `.ci` was there for no good reason. I fixed it in #119.

**Comment by hongyi-zhao** [comment]
Another question is: As I’ve noticed from the workflow configuration used in many projects, say, [here](https://github.com/spglib/spglib/tree/develop/.github/workflows) and [here](https://github.com/vufa/deepin-wine-wechat-arch/tree/action/.github/workflows), all the configuration files are located under `.github/workflows`.  But this project uses a different configuration files layout, with the codecov.yml located at [here](https://github.com/wannier-berri/wannier-berri/blob/master/.github/codecov.yml). Is it randomly placed like this or is there any other special purpose?

**Comment by jaemolihm** [comment]
No, there is no specific reason.
