### ISSUE TITLE
Has `wannier-berri` already implemented the method described in https://doi.org/10.1103/PhysRevB.99.235113?

### ISSUE THREAD

**Issue by hongyi-zhao** [wannier-berri/wannier-berri#121]
Today, when I'm reading [this paper](https://doi.org/10.1103/PhysRevB.104.014412), I noticed the following statement in the `ACKNOWLEDGMENTS` section:

```
We thank Jun Zhou and Jiaqi Zhou for their helpful
discussions on the technical details, and Minsu Ghim for de-
veloping and sharing the code to test Ryoo’s method [45].

[45] J. H. Ryoo, C.-H. Park, and I. Souza, Computation of intrinsic
spin Hall conductivities from first principles using maximally
localized Wannier functions, Phys. Rev. B 99, 235113 (2019).
```

And I also find the [`WannierBerri`](https://github.com/manxkim/WannierBerri) project, which seems to be  adapted from a fairly early version of `wannier-berri`. So, I want to know if the current version of `wannier-berri` has already implemented the method  described in https://doi.org/10.1103/PhysRevB.99.235113. See [here](https://github.com/manxkim/WannierBerri/issues/1) for the relevant issue.

Regards,
HZ

**Comment by jaemolihm** [comment]
Yes, please see the documentation https://wannier-berri.org/capabilities.html.

For questions, please use GitHub Discussions (https://github.com/wannier-berri/wannier-berri/discussions) or mailing list.

**Comment by hongyi-zhao** [comment]
May we should always add the paper's URL, say, for this case: https://journals.aps.org/prb/abstract/10.1103/PhysRevB.99.235113, into the source code, so that even if users do not browse the documents carefully, they still can easily find relevant original documents by searching the source code, for example, by `grep -nRi PhysRevB.99.235113`.
