### ISSUE TITLE
About SHC tensors shape

### ISSUE THREAD

**Issue by ggurung1** [wannier-berri/wannier-berri#128]
Hello developers,
I found out that the order  of the SHC (with omega=0) tensors printed out is not same with the other published codes. The magnitude of the nonzero  (e.g. a, b and c) components are of the same order and comparable in magnitude (difference in magnitude may be because the code uses different eta=0 .1 eV in the SHC formula). 

For example, I got shc=[[[0,0,0],[0,a,0],[0,b,0]],[[0,0,-a],[0,0,0],[-b,0,0]],[[0,c,0],[-c,0,0],[0,0,0]]] for the other code 
                And shc=[[[0,0,0],[0,c,0],[0,a,0]],[[0,0,-c],[0,0,0],[-a,0,0]],[[0,b,0],[-b,0,0],[0,0,0]] using wannierberri.

I use the same wannier90_hr.dat file, pseudopotentials and input for all the case.

Can you please check whether the order in which the SHC tensors is printed out?

**Comment by stepan-tsirkin** [comment]
@ggurung1 , could you specify, what is "the other code" ?

**Comment by ggurung1** [comment]
@stepan-tsirkin  I used paoflow and wannierlinearresponse code. Both give same shape tensor.

**Comment by jaemolihm** [comment]
Hi @ggurung1 ,
The WannierBerri convention is shc[i_fermi, alpha, beta, gamma], where alpha, beta, gamma are defined in https://wannier-berri.org/capabilities.html.

The other codes may be using different ordering of the three indices. Could you check which ordering they use?

**Comment by ggurung1** [comment]
Thank you @jaemolihm. I found the ordering is different.
