### ISSUE TITLE
Symmetrization of Hamiltonian and atomic orbitalized Wannier function.

### ISSUE THREAD

**Issue by hongyi-zhao** [wannier-berri/wannier-berri#129]
I've noticed there are two similar tools available currently, which aim to implement the symmetrization of the Hamiltonian and atomic orbital Wannier functions based on the results of wannier90: [wannhr_symm](https://github.com/quanshengwu/wannier_tools/tree/master/utility/wannhr_symm) and [WannSymm](https://github.com/ccao/WannSymm). Considering that wannier-berri is a more feature-rich wannier90 post-processing tool. So, I wonder if there is a plan to provide this functionality in wannier-berri too. See [here](https://github.com/ccao/WannSymm/issues/5) and [here](https://github.com/wannier-developers/wannier90/issues/390) for the related discussions.

Regards,
HZ

**Comment by stepan-tsirkin** [comment]
There is currently a PR #89, which is still being tested. When finished, it will be able to symmetrize not inly the Hamiltonian, but also other matrix elements needed for Wannier interpolation, e.g. position matrix wlements, spin matrix, etc.

**Comment by hongyi-zhao** [comment]
> There is currently a PR #89, which is still being tested.

Thank you for pointing this out. It seems the creater of this PR,  Xiaoxiong Liu, is a member of your group and a PhD student now, according to the information [here](https://www.physik.uzh.ch/en/groups/neupert/team/Xiaoxiong-Liu.html) and [here](https://www.physik.uzh.ch/en/groups/neupert/Software.html).

**Comment by stepan-tsirkin** [comment]
@hongyi-zhao , this was completed
