### ISSUE TITLE
Script for ray for a PBS cluster is broken

### ISSUE THREAD

**Issue by jaemolihm** [wannier-berri/wannier-berri#149]
https://physik.lists.uzh.ch/sympa/arc/wannier-berri/2022-04/msg00000.html

**Comment by HeejuKim95** [comment]
Hello.
Here are PBS script, output and error log files.


[result_wb.txt](https://github.com/wannier-berri/wannier-berri/files/8422936/result_wb.txt)
[wb_CT_py.o10003759.log](https://github.com/wannier-berri/wannier-berri/files/8422937/wb_CT_py.o10003759.log)
[wb-16nodes_0403-020618.sh.txt](https://github.com/wannier-berri/wannier-berri/files/8422938/wb-16nodes_0403-020618.sh.txt)
[wb_CT_py.e10003759.log](https://github.com/wannier-berri/wannier-berri/files/8422939/wb_CT_py.e10003759.log)

**Comment by jaemolihm** [comment]
Hi, thanks for sharing the files! Could you try the following script?

Note that there is no space next to "=". I also added some print statements for debugging. (See the diff below)

```bash
#!/bin/sh
#PBS -N wb_CT_py
#PBS -l select=16:ncpus=64:mpiprocs=1:ompthreads=1
#PBS -q normal
#PBS -l walltime=48:00:00
#PBS -A etc
#PBS -m abe
#PBS -M ds2bkz1@naver.com

cd $PBS_O_WORKDIR
export OMP_NUM_THREADS=1


module purge
module load python/3.7
module load craype-mic-knl intel/19.0.5 impi/19.0.5
source activate wb

################# DON NOT CHANGE THINGS HERE UNLESS YOU KNOW WHAT YOU ARE DOING ###############

# This script is taken and modified from https://github.com/ray-project/ray/issues/10466#issuecomment-737476909

jobnodes=`uniq -c $PBS_NODEFILE | awk -F. '{print $1 }' | awk '{print $2}' | paste -s -d " "`

redis_password=$(uuidgen)
export redis_password

thishost=`uname -n | awk -F. '{print $1.}'`
ip=`hostname -i`
port=6379
ip_head="$ip:$port"
ray_command=$(which ray)
export ip_head
echo "RAY command: $ray_command"
echo "IP Head: $ip_head"

echo "Allocate Nodes = <$jobnodes>"

echo "set up ray cluster..."
for node in `echo $jobnodes`; do
    if [[ $node == "$thishost" ]]; then
        echo "STARTING HEAD at $node"
        ray start --head --node-ip-address=$ip --port=$port --redis-password=$redis_password --block &
        sleep 30.0
    else
        echo "STARTING WORKER at $node"
        echo "RUNNING $ray_command start --address=$ip_head --redis-password=$redis_password"
        ssh $node "$ray_command start --address=$ip_head --redis-password=$redis_password"
        sleep 5.0
    fi
done

##############################################################################################

#### call your code below
python3 -u AHE.py 16-nodes > result_wb.txt
```


```diff
32c32
< ray_command = $(which ray)
---
> ray_command=$(which ray)
33a34
> echo "RAY command: $ray_command"
45a47
>         echo "RUNNING $ray_command start --address=$ip_head --redis-password=$redis_password"
```

**Comment by HeejuKim95** [comment]
I tried but I still have some errors.

Here are my PBS script, output and error log files, again.

Thanks.

[result_wb.txt](https://github.com/wannier-berri/wannier-berri/files/8424596/result_wb.txt)
[wb_CT_py.e10005775.log](https://github.com/wannier-berri/wannier-berri/files/8424615/wb_CT_py.e10005775.log)
[wb_CT_py.o10005775.log](https://github.com/wannier-berri/wannier-berri/files/8424616/wb_CT_py.o10005775.log)
[wb_new.sh.txt](https://github.com/wannier-berri/wannier-berri/files/8424617/wb_new.sh.txt)

**Comment by jaemolihm** [comment]
I think there may be an actual memory issue. Your system is quite large (272 WFs, `NKFFT=[17 17  8]`). Each component of matrices will allocate `272^2 * 17 * 17 * 8 * 16(complex) ~ 2.7 GB` of memory.

Please try to reduce the memory usage by setting NKFFT to a smaller value. For example, `grid=wberri.Grid(system, NKFFT=[2,2,2], NKdiv=[8, 8, 4])`.

**Comment by HeejuKim95** [comment]
Thanks, I will try again.
By the way, I am using 16 nodes, total 16 cores and each of core has memory of 80GB.
Isn't this memory enough?

**Comment by jaemolihm** [comment]
Your script says `select=16:ncpus=64:mpiprocs=1:ompthreads=1`. As far as I understand, this means that you are using 16 nodes and 64 CPUs per node, so the memory per CPU would be 80 / 64 ~ 1.25 GB.

**Comment by stepan-tsirkin** [comment]
I agree with @jaemolihm , and also note:

parallelization is done over K-point (FFT grids) not k-points within a FFT grid. So, what you are doing is actually not in parallel, because 

```
The grids were set to NKdiv=[1 1 1], NKFFT=[17 17  8], NKtot=[17 17  8]
...
processing 1 K points : using  1088 processes.
```

However, I am not sure why a memory issue arises, because actually only one process is running, so 80GB on its node should be enough, in principle. 

Anyway, try to reduce NKFFT first (in principle it can be as low as 1x1x1

**Comment by jaemolihm** [comment]
Maybe the problem is that ray cluster uses all cores, ignoring the ncpus and mpiprocs arguments of PBS...

**Comment by HeejuKim95** [comment]
Thanks, @stepan-tsirkin and @jaemolihm .
I'll give it a try and let you know the results when the job is done.

But I don't really understand. 

I asked the server administrator about memory usage.
The queue I use now can use 80GB per node.
Also, `select` is the number of nodes, `ncpus` is the number of cpu cores to use, and `mpiprocs` is the number of processes per node to use.

Here are some examples that the administrator gave me.:
[example]
-1 node, performing work with a total of 40 cores: about 2 GB of memory per 1 core (80 GB / 40)
`#PBS -l select=1:ncpus=64:mpiprocs=40:ompthreads=1`

-2 nodes, performing tasks with a total of 40 cores: About 4 GB of memory per core (80 GB / 20)
`#PBS -l select=2:ncpus=64:mpiprocs=20:ompthreads=1`

Even if the job that I performed was not in parallel, I think the memory was enough.

**Comment by HeejuKim95** [comment]
I am not sure if this can be a hint but I actually got `wannier90-ahc_iter-0000.dat` file once before.
(Anyway I couldn't get iter-0001.dat or more.)

At that time, I used another queue with memory of ~170GB per node.
But then, I did not know that I need to add something on the PBS script.

Here I attach some files that I used at that time.
[CT_py.e9937437.log](https://github.com/wannier-berri/wannier-berri/files/8428835/CT_py.e9937437.log)
[result_wb.txt](https://github.com/wannier-berri/wannier-berri/files/8428837/result_wb.txt)
[AHE.py.txt](https://github.com/wannier-berri/wannier-berri/files/8428838/AHE.py.txt)

I also got Klist.pickle and output log file but both of them were empty.

I hope this can be a hint for this issue.

**Comment by HeejuKim95** [comment]
Hi, I finished several jobs with changing to the input: `grid=wberri.Grid(system, NKFFT=[2,2,2], NKdiv=[8, 8, 4])`.

Moreover, I tried 3 different PBS scripts to get some ideas.

1. Using queue with memory of 170 GB per node and `select=16:ncpus=40:mpiprocs=20:ompthreads=1`
[wb_CT_py.e10010384.log](https://github.com/wannier-berri/wannier-berri/files/8448392/wb_CT_py.e10010384.log)
[wb_CT_py.o10010384.log](https://github.com/wannier-berri/wannier-berri/files/8448393/wb_CT_py.o10010384.log)
[10010384_result_wb.txt](https://github.com/wannier-berri/wannier-berri/files/8448395/10010384_result_wb.txt)
[wb_new.sh.txt](https://github.com/wannier-berri/wannier-berri/files/8448397/wb_new.sh.txt)

2. Using queue with memory of 80 GB per node and `select=100:ncpus=68:mpiprocs=20:ompthreads=1`
[wb_CT_py.e10010912.log](https://github.com/wannier-berri/wannier-berri/files/8448421/wb_CT_py.e10010912.log)
[wb_CT_py.o10010912.log](https://github.com/wannier-berri/wannier-berri/files/8448422/wb_CT_py.o10010912.log)
[10010912_result_wb.txt](https://github.com/wannier-berri/wannier-berri/files/8448457/10010912_result_wb.txt)
[wb_new.sh.txt](https://github.com/wannier-berri/wannier-berri/files/8448423/wb_new.sh.txt)

3. Using queue with memory of 80 GB per node and `select=16:ncpus=68:mpiprocs=1:ompthreads=1`
[wb_CT_py.e10010651.log](https://github.com/wannier-berri/wannier-berri/files/8448454/wb_CT_py.e10010651.log)
[wb_CT_py.o10010651.log](https://github.com/wannier-berri/wannier-berri/files/8448455/wb_CT_py.o10010651.log)
[10010651_result_wb.txt](https://github.com/wannier-berri/wannier-berri/files/8448477/10010651_result_wb.txt)
[wb_new.sh.txt](https://github.com/wannier-berri/wannier-berri/files/8448456/wb_new.sh.txt)

**Comment by jaemolihm** [comment]
Thanks for testing various configurations. It seems that the memory problem still exists.

> Maybe the problem is that ray cluster uses all cores, ignoring the ncpus and mpiprocs arguments of PBS...

I think this may be the reason. Could you add `--num-cpus=1` (or whatever cpus per node you want) to the ray start commands? I found that this limits the number of ray processes.
```bash
echo "set up ray cluster..."
for node in `echo $jobnodes`; do
    if [[ $node == "$thishost" ]]; then
        echo "STARTING HEAD at $node"
        ray start --head --node-ip-address=$ip --port=$port --redis-password=$redis_password --block --num-cpus=1 &
        sleep 30.0
    else
        echo "STARTING WORKER at $node"
        echo "RUNNING $ray_command start --address=$ip_head --redis-password=$redis_password --num-cpus=1"
        ssh $node "$ray_command start --address=$ip_head --redis-password=$redis_password --num-cpus=1"
        sleep 5.0
    fi
```

**Comment by HeejuKim95** [comment]
Thanks, it seems to work with `--num-cpus=1` and `grid=wberri.Grid(system, NKFFT=[2,2,2], NKdiv=[8, 8, 4])`.

I want to make the grid a little denser because I want to increase the accuracy. In this case, can it be solved by using a larger number of nodes?

**Comment by jaemolihm** [comment]
Great that it works! Yes, using more nodes would make calculation faster. Also, you could try increasing `--num-cpus` (up to the point where the memory problem does not occur) to further enhance the parallel performance.

To increase the grid size, I could recommend fixing NKFFT to a small value (you could also test this: Fix NKFFT*NKdiv and see whether increasing NKFFT makes calculation faster without causing the memory issue), and increasing NKdiv as you want.
