### ISSUE TITLE
Undefined variable in __sym_wann.py

### ISSUE THREAD

**Issue by jaemolihm** [wannier-berri/wannier-berri#153]
The variable `ir` is not defined. @Liu-Xiaoxiong could you fix this?

https://github.com/wannier-berri/wannier-berri/blob/696e849773be7e108a0dcc8f0c94fca319a6b135/wannierberri/__sym_wann.py#L262

**Comment by Liu-Xiaoxiong** [comment]
Sorry! I give a comment in #154 . Could you please change it?
