### ISSUE TITLE
Allow testing without installing ase and gpaw

### ISSUE THREAD

**Issue by jaemolihm** [wannier-berri/wannier-berri#171]

**Comment by stepan-tsirkin** [comment]
Agree, also without pythtb and tbmodels

**Comment by jaemolihm** [comment]
Done for gpaw and ase: https://github.com/wannier-berri/wannier-berri/pull/195

pythtb and tbmodels are quite light and easy; also I think they already are not required because there is no global `import pythtb`, but but I haven't tested.
