### ISSUE TITLE
The errors of vaspspn.py

### ISSUE THREAD

**Issue by hahArcher1** [wannier-berri/wannier-berri#181]
hello developers, I want to use the vaspspn.py to get the wannier90.spn file from WAVECAR. But when I execute the program，I find some errors.  Maybe this code "from wanierberri.__utility import FortranFileW" in vaspspn.py should change into "from wannierberri.__utility import FortranFileW"  with double n.

Thank you for developing and sharing such a great program!

**Comment by stepan-tsirkin** [comment]
@hahArcher1 , thanks for spotting the typo,

Do you wish to make a PR, so that your profile appears among contributors?

**Comment by jaemolihm** [comment]
Closed by #199
