### ISSUE TITLE
Not enough memory

### ISSUE THREAD

**Issue by ngohainc** [wannier-berri/wannier-berri#186]
Hello developers, I am calculating the anomalous Hall conductivity on the cell of 18 atoms and facing a serious problem with RAM memory for the parallel execution. Although I have reduced the number of parallel processes to a minimum as bellow

parallel=wberri.Parallel(method="ray", num_cpus=2)

However, all 96 Gb of the computer's RAM  is still not enough.

Please, tell us to solve this issue.
Thank you very much!

![z3478377241963_21a55b3385bcc98a28f5f539c9f0f2c3](https://user-images.githubusercontent.com/107199859/172882012-037385e6-f643-464c-b1ce-175cd5e0d396.jpg)

p/s: As I know when using VASP, the memory requirements per core can be reduced significantly by adjusting NCORE, LREAL, KPAR..etc.

**Comment by stepan-tsirkin** [comment]
@ngohainc  , how many Wannier Functions do you have? The memory requirement may be reduced by decreasing the FFT grid in the Grid() object (while keeping the same full grid), like `Grid(length=100,NKFFT=4)`. 

This comes at some expense of the speed of FFT transform, but a good balance may be found.

**Comment by ngohainc** [comment]
Thank Developer very much for your helpful advice. Yes, the issue has been solved. The program can run smoothly with 6 parallel processes now.  I use 380 Wannier Functions in total.

There is a minor thing bothering me when applying the new setting, that is:
I set length=200 and it is converted into NK=[50 50 14]
I can see that the third component of the grid (14) is quite small as compared to the two first components (50). So, does it affect the reliability of the result? 
The unit cell of the compound I investigate is Hcp type.

**Comment by stepan-tsirkin** [comment]
380 WFs is quite a lot. Glad to hear that it still works. 

The grid is automatically chosen such that the spacing between k-points is approximately equal in all directions. I guess your hcp unit cell has c/a ~=3 , i.e. the Brillouin zone is short in the z direction. If you have reasoning why denser sampling in kz is needed in your case, you may set the grids manually using parameters NK, NKdiv, NKFFT.

**Comment by ngohainc** [comment]
Yes, I got you.

Thank you for developing and sharing such a great program!
