### ISSUE TITLE
error reading wannier90_hr.dat

### ISSUE THREAD

**Issue by tpyang** [wannier-berri/wannier-berri#198]
I am trying to read a standard wannier90_hr.dat (Wannier90 (v3.1.0)) using:
system=wberri.System_tb('wannier90_hr.dat')

It seems it only supports tb.dat file, is wannier90_hr.dat supported in the program?

**Comment by jaemolihm** [comment]
No, you need the tb.dat file.

Other way is to call `wberri.System_w90(seedname='wannier90')`. This way provides more functionalities, and you do not need any additional files except the usual Wannier90 input and output (mmn, chk).
