### ISSUE TITLE
 Numba problem : cannot import name 'npdatetime_helpers' from 'numba.np' 

### ISSUE THREAD

**Issue by HeejuKim95** [wannier-berri/wannier-berri#237]
Hello, developers!

I'm having trouble using calculators in wannierberri.

Here are the error messages I got:

```
import wannierberri as wberri
  File "/home01/h/.conda/envs/wb/lib/python3.8/site-packages/wannierberri/__init__.py", line 19, in <module>
    from .run import run
  File "/home01/h/.conda/envs/wb/lib/python3.8/site-packages/wannierberri/run.py", line 20, in <module>
    from .data_K import Data_K
  File "/home01/h/.conda/envs/wb/lib/python3.8/site-packages/wannierberri/data_K.py", line 20, in <module>
    from .__tetrahedron import TetraWeights, get_bands_in_range, get_bands_below_range
  File "/home01/h/.conda/envs/wb/lib/python3.8/site-packages/wannierberri/__tetrahedron.py", line 14, in <module>
    from numba import njit
  File "/home01/h/.local/lib/python3.8/site-packages/numba/__init__.py", line 20, in <module>
    from numba.core import types, errors
  File "/home01/h/.local/lib/python3.8/site-packages/numba/core/types/__init__.py", line 12, in <module>
    from .scalars import *
  File "/home01/h/.local/lib/python3.8/site-packages/numba/core/types/scalars.py", line 9, in <module>
    from numba.npimport npdatetime_helpers
ImportError: cannot import name 'npdatetime_helpers' from numba.np (unknown location)
```

I didn't install numba on my own, it was installed during the wannierberri upgrade by iteself.
The versions of numba and wannierberri are 0.56.4. and 0.13.5., respectively.

I also attach the results of 'pip list' and 'conda list' here:

`$ pip3 list`
Package                  Version
aiohttp                  3.8.1
aiohttp-cors             0.7.0
aioredis                 1.3.1
aiosignal                1.2.0
async-timeout            4.0.2
attrs                    21.4.0
blessed                  1.19.1
cachetools               5.0.0
certifi                  2021.10.8
charset-normalizer       2.0.12
click                    8.1.2
colorama                 0.4.4
colorful                 0.5.4
cycler                   0.11.0
defusedxml               0.7.1
Deprecated               1.2.13
filelock                 3.6.0
fonttools                4.31.2
fortio                   0.4
frozenlist               1.3.0
google-api-core          2.7.1
google-auth              2.6.2
googleapis-common-protos 1.56.0
gpustat                  1.0.0b1
grpcio                   1.43.0
hiredis                  2.0.0
idna                     3.3
importlib-metadata       6.0.0
importlib-resources      5.6.0
jsonschema               4.4.0
kiwisolver               1.4.2
lazy-property            0.0.1
llvmlite                 0.39.1
matplotlib               3.5.1
mpmath                   1.2.1
msgpack                  1.0.3
multidict                6.0.2
numba                    0.56.4
numpy                    1.21.5
nvidia-ml-py3            7.352.0
opencensus               0.8.0
opencensus-context       0.1.2
packaging                21.3
Pillow                   9.1.0
pip                      21.2.4
prometheus-client        0.13.1
protobuf                 3.20.2
psutil                   5.9.0
py-spy                   0.3.11
pyasn1                   0.4.8
pyasn1-modules           0.2.8
pyFFTW                   0.13.0
pyfiglet                 0.8.post1
pyparsing                3.0.7
pyrsistent               0.18.1
python-dateutil          2.8.2
PyYAML                   6.0
ray                      1.11.0
redis                    4.2.2
requests                 2.27.1
rsa                      4.8
scipy                    1.8.0
setuptools               58.0.4
six                      1.16.0
smart-open               5.2.1
spglib                   1.16.5
sympy                    1.11.1
termcolor                1.1.0
untangle                 1.2.1
urllib3                  1.26.9
wannierberri             0.13.5
wcwidth                  0.2.5
wheel                    0.37.1
wrapt                    1.14.0
yarl                     1.7.2
zipp                     3.8.0

`$ conda list`
 Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
aiohttp                   3.8.1                     <pip>
aiohttp-cors              0.7.0                     <pip>
aioredis                  1.3.1                     <pip>
aiosignal                 1.2.0                     <pip>
async-timeout             4.0.2                     <pip>
attrs                     21.4.0                    <pip>
blessed                   1.19.1                    <pip>
ca-certificates           2022.3.29            h06a4308_0  
cachetools                5.0.0                     <pip>
certifi                   2021.10.8        py38h06a4308_2  
charset-normalizer        2.0.12                    <pip>
click                     8.1.2                     <pip>
colorama                  0.4.4                     <pip>
colorful                  0.5.4                     <pip>
cycler                    0.11.0                    <pip>
defusedxml                0.7.1                     <pip>
Deprecated                1.2.13                    <pip>
filelock                  3.6.0                     <pip>
fonttools                 4.31.2                    <pip>
fortio                    0.4                       <pip>
frozenlist                1.3.0                     <pip>
google-api-core           2.7.1                     <pip>
google-auth               2.6.2                     <pip>
googleapis-common-protos  1.56.0                    <pip>
gpustat                   1.0.0b1                   <pip>
grpcio                    1.43.0                    <pip>
hiredis                   2.0.0                     <pip>
idna                      3.3                       <pip>
importlib-metadata        6.0.0                     <pip>
importlib-resources       5.6.0                     <pip>
jsonschema                4.4.0                     <pip>
kiwisolver                1.4.2                     <pip>
lazy-property             0.0.1                     <pip>
ld_impl_linux-64          2.35.1               h7274673_9  
libffi                    3.3                  he6710b0_2  
libgcc-ng                 9.1.0                hdf63c60_0  
libstdcxx-ng              9.1.0                hdf63c60_0  
llvmlite                  0.39.1                    <pip>
matplotlib                3.5.1                     <pip>
mpmath                    1.2.1                     <pip>
msgpack                   1.0.3                     <pip>
multidict                 6.0.2                     <pip>
ncurses                   6.3                  h7f8727e_2  
numba                     0.56.4                    <pip>
numpy                     1.21.5                    <pip>
nvidia-ml-py3             7.352.0                   <pip>
opencensus                0.8.0                     <pip>
opencensus-context        0.1.2                     <pip>
openssl                   1.1.1n               h7f8727e_0  
packaging                 21.3                      <pip>
Pillow                    9.1.0                     <pip>
pip                       21.2.4           py38h06a4308_0  
prometheus-client         0.13.1                    <pip>
protobuf                  3.20.2                    <pip>
psutil                    5.9.0                     <pip>
py-spy                    0.3.11                    <pip>
pyasn1                    0.4.8                     <pip>
pyasn1-modules            0.2.8                     <pip>
pyFFTW                    0.13.0                    <pip>
pyfiglet                  0.8.post1                 <pip>
pyparsing                 3.0.7                     <pip>
pyrsistent                0.18.1                    <pip>
python                    3.8.12               h12debd9_0  
python-dateutil           2.8.2                     <pip>
PyYAML                    6.0                       <pip>
ray                       1.11.0                    <pip>
readline                  8.1.2                h7f8727e_1  
redis                     4.2.2                     <pip>
requests                  2.27.1                    <pip>
rsa                       4.8                       <pip>
scipy                     1.8.0                     <pip>
setuptools                58.0.4           py38h06a4308_0  
six                       1.16.0                    <pip>
smart-open                5.2.1                     <pip>
sqlite                    3.38.2               hc218d9a_0  
sympy                     1.11.1                    <pip>
termcolor                 1.1.0                     <pip>
tk                        8.6.11               h1ccaba5_0  
untangle                  1.2.1                     <pip>
urllib3                   1.26.9                    <pip>
wannierberri              0.13.5                    <pip>
wcwidth                   0.2.5                     <pip>
wheel                     0.37.1             pyhd3eb1b0_0  
wrapt                     1.14.0                    <pip>
xz                        5.2.5                h7b6447c_0  
yarl                      1.7.2                     <pip>
zipp                      3.8.0                     <pip>
zlib                      1.2.11               h7f8727e_4

**Comment by stepan-tsirkin** [comment]
Hi @HeejuKim95  that is weird, because I am using the same numba-0.56.4, could you run your python interpreter and execute the following commands:
```
$ python
Python 3.9.13 (main, Aug 25 2022, 23:26:10) 
[GCC 11.2.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from numba.np import npdatetime_helpers
>>> import numba
>>> numba.__version__
'0.56.4'
>>> 
```
Do you get the same error?

**Comment by HeejuKim95** [comment]
Yes, I do.

$ python3

Python 3.8.12 (default, Oct 12 2021, 13:49:34) 
[GCC 7.5.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from numba.np import npdatetime_helpers
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home01/h/.local/lib/python3.8/site-packages/numba/__init__.py", line 20, in <module>
    from numba.core import types, errors
  File "/home01/h/.local/lib/python3.8/site-packages/numba/core/types/__init__.py", line 12, in <module>
    from .scalars import *
  File "/home01/h/.local/lib/python3.8/site-packages/numba/core/types/scalars.py", line 9, in <module>
    from numba.np import npdatetime_helpers
ImportError: cannot import name 'npdatetime_helpers' from 'numba.np' (unknown location)
>>> import numba
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home01/h/.local/lib/python3.8/site-packages/numba/__init__.py", line 20, in <module>
    from numba.core import types, errors
  File "/home01/h/.local/lib/python3.8/site-packages/numba/core/types/__init__.py", line 12, in <module>
    from .scalars import *
  File "/home01/h/.local/lib/python3.8/site-packages/numba/core/types/scalars.py", line 9, in <module>
    from numba.np import npdatetime_helpers
ImportError: cannot import name 'npdatetime_helpers' from 'numba.np' (unknown location)

**Comment by HeejuKim95** [comment]
Thank you. I solved the problem.
I think the old version and the new version of numba was mixed.
I unistalled and installed it again, and the problem was solved.

**Comment by stepan-tsirkin** [comment]
Great!
