### ISSUE TITLE
fermisurfer shows no berry curvature

### ISSUE THREAD

**Issue by Vahid999** [wannier-berri/wannier-berri#291]
Hi,

I used the following input to get the 3D grid curvature:

import wannierberri as wberri
import pyfftw 
import numpy as np
import scipy
import matplotlib.pyplot as plt
from termcolor import cprint

system=wberri.System_w90(seedname='wannier90',berry=True,fft='numpy')

grid=wberri.Grid(system,length=200)

parallel=None

EF=11.8795

tabulators = { "Energy": wberri.calculators.tabulate.Energy(),
               "berry" : wberri.calculators.tabulate.BerryCurvature(),
             }

tab_all_grid = wberri.calculators.TabulatorAll(
                    tabulators,
                    ibands = np.arange(10,70),
                    mode = "grid"
                        )

result=wberri.run(system, 
             grid=grid,
             calculators = {"tabulate" : tab_all_grid},
             parameters_K = dict( fftlib = "numpy" ))

print (result.results)
grid_result = result.results["tabulate"]

The attached file shows the output of the serial run. But the fermisurfer output just shows the unit cell with no berry curvature. Does anyone know what might be causing this?

Thanks,
Vahid

[berry.out.zip](https://github.com/wannier-berri/wannier-berri/files/13358215/berry.out.zip)

**Comment by stepan-tsirkin** [comment]
It is hard to say without seeing your frmsf file, but let me guess. Did you set the "Fermi energy" parameter in fermisurfer
![image](https://github.com/wannier-berri/wannier-berri/assets/22172977/ddca314b-532f-4ac6-9d40-15e5448fcbd0)

nite, in your script the line `EF=11.8795` is bever used, so fermisurfer does not know where the Fewrmi level is.

If I did not guess correctly, could you upload your frmsf file (probably with a reduced grid, if the file gets is too big) as well as a screenshot of what you have in fermisurfer.

**Comment by Weian-Guo** [comment]
hello Dr. stepan:
I have enter the fermi level into the fermisurfer and the software shows the fermi surface but still do not show the berry curvature, I do not understand the resean beyond. I attached the screen shot and result file, could you please show me why is that ? 
![屏幕截图 2023-11-22 205946](https://github.com/wannier-berri/wannier-berri/assets/151745178/69f3e51f-ddfa-46aa-8b40-074158124540)
[result-tabulate_berry-z.zip](https://github.com/wannier-berri/wannier-berri/files/13439545/result-tabulate_berry-z.zip)

**Comment by stepan-tsirkin** [comment]
@Weian-Guo , the reason is simple - the Berry curvature is zero in your file:

![image](https://github.com/wannier-berri/wannier-berri/assets/22172977/6b3bab60-0245-4cbb-8b66-49db9737170e)

But why that happened - is another question. What is the material and what script you run to calculate this?

**Comment by Weian-Guo** [comment]
![dbd8f9aba9ab8baa8ee7c1dc798e563](https://github.com/wannier-berri/wannier-berri/assets/151745178/2bfee87f-d2bc-4142-b990-a2e416bf9208)
![f61ea42c0a4ecfbb674ae84de68c304](https://github.com/wannier-berri/wannier-berri/assets/151745178/7e6298dd-ae1d-4957-bb46-2f238779e918)
![fe671ddf336ed51b72531145865d3cf](https://github.com/wannier-berri/wannier-berri/assets/151745178/994e10d7-34c3-4f8c-9bd9-2c23b22e105a)
[POSCAR.zip](https://github.com/wannier-berri/wannier-berri/files/13446893/POSCAR.zip)
Hello, Dr.Stepan, these png files is the script I used to calculate Berry curvature in 3D Brillouin zone, the calculation progress seems no problem and also produced .frmsf file, I'll very appriciate for your help. I just started to use wannierberri one weeks ago , I love this software.

**Comment by stepan-tsirkin** [comment]
@Weian-Guo in `set_structure` you did not specify magnetic moments on each atom, therefore they are assumed zero, so system is assumed to have time-reversal symmetry (T). In addition, you structure has inversion, so I*T kills any berry curvature when symmetrization is done during a grid calculation. You should either specify the directions of the magnetic moments (look for them in the OUTCAR file, but keep in mind that there they may be not really symmetric due to numerical errors) or set symmetries manually using [`set_symmstry`](https://docs.wannier-berri.org/en/master/docs/system.html#wannierberri.system.System.set_symmetry() ) method, or switch off symmetrization in [`run ( .. use_irred_kpt=False, symmetrize=False)`](https://docs.wannier-berri.org/en/master/docs/run.html#wannierberri.run)

Note, on the path calculation symmetrization is not performed, so `set_symmetries_from_structure` has no effect on that.

**Comment by Weian-Guo** [comment]
![a558864b671ab1bcb7e4796a3eef933](https://github.com/wannier-berri/wannier-berri/assets/151745178/bcae6df0-80ca-4433-8a3e-957d9f41a42b)
Hello, Dr.Stepan, sorry to bother you, when I test the example of Fe crystall , I try to specify the magnetic moments on each atom just as what you told me , but when I specify the magnetic moments in both system.set_structure() and system.symmetrize() at the same time, the code always have such error, I could not figure out the reason，can you help me ?

**Comment by Weian-Guo** [comment]
![515e9ff24e6a04d330292ec47622003](https://github.com/wannier-berri/wannier-berri/assets/151745178/e2fcdf5d-ebbb-40a1-b83e-acc0965686df)
![d5d2d4c17f4d8b9b2a3c22776cf60a6](https://github.com/wannier-berri/wannier-berri/assets/151745178/b26aa220-24df-4804-9d17-906fd94fb826)
Hello, Dr.Stepan, sorry to bother you, when I test the example of Fe crystall , I try to specify the magnetic moments on each atom just as what you told me , but when I specify the magnetic moments in both system.set_structure() and system.symmetrize() at the same time, the code always have such error, I could not figure out the reason，could you give me some advice?

**Comment by Weian-Guo** [comment]
![38dcb75b6e183ccdeb691d145a69873](https://github.com/wannier-berri/wannier-berri/assets/151745178/41f328e7-5bac-474a-9aaa-77960d6c8348)
![ce7cf152d1d0734dc8d3c53d8490f98](https://github.com/wannier-berri/wannier-berri/assets/151745178/1903935e-ba0a-461d-bd47-a840f673c70a)
![0e70f20fdb9c76c1c97a661a4760687](https://github.com/wannier-berri/wannier-berri/assets/151745178/59040e14-3b
![a5c61f9e80f53f089ca50cd3ea5ede8](https://github.com/wannier-berri/wannier-berri/assets/151745178/058be575-a05b-4536-9005-ccd13a3eb155)
74-4f9f-871d-23e6953d9b71)
Hello, Dr.Stepan.Tsirkin, sorry to bother you , I specified the magnetic moment in the set_structure() and specified the use_irred_kpt=False, symmetrize=False in run() just as what you taught me, and I use the script you have used above to check the output of the Berry curvature. the value is not zero. But when I use the fermisurfer to visualize the .frmsf file, it still can not show the Berry curvature, this really confused me , could you give me some advice ? the .frmsf file is too big to upload, I have send the file via the email

**Comment by stepan-tsirkin** [comment]
@Weian-Guo  you need to adjust the colorscale min and max values

![image](https://github.com/wannier-berri/wannier-berri/assets/22172977/c8a4fb0d-3e42-4c5c-b4b8-e6cfb426786c)
