### ISSUE TITLE
Recentering off-diagonal translation invariant matrix elements after do_ws_dist()

### ISSUE THREAD

**Issue by sjhong6230** [wannier-berri/wannier-berri#309]
Dear developers,

The current transl_inv_OSD branch recenters the off-diagonal translation invariant matrix elements after the `do_ws_dist()` function.

However, doing so sometimes fails the assertion in the `do_ws_dist()` function for the CC matrix, and moving the recentering to before `do_ws_dist()` resolved this issue in my computation. 

If my memory is correct, the old version of the transl_inv_OSD branch recentered the matrix elements before `do_ws_dist()`, but at some time, it changed to the current version.

Is there a specific reason for moving the recentering from before to after `do_ws_dist()`?

Below are the files I used for the computation.
[Fe.input.tar.gz](https://github.com/wannier-berri/wannier-berri/files/14150036/Fe.input.tar.gz)

Best,
Seung-Ju

**Comment by stepan-tsirkin** [comment]
@sjhong6230 , the current implementation is in the state of a PR #308 . Note that you may comment on the changes right there. ( Go to "files changed", find the corresponding line and put a comment )

@scarpoz had a strong reason to do that. 

Could you point which assertion fails?

**Comment by sjhong6230** [comment]
> @sjhong6230 , the current implementation is in the state of a PR #308 . Note that you may comment on the changes right there. ( Go to "files changed", find the corresponding line and put a comment )
> 
> @scarpoz had a strong reason to do that.
> 
> Could you point which assertion fails?

https://github.com/wannier-berri/wannier-berri/blob/d6646d7efceb65a68989692b547f1c7e5dc0d4bb/wannierberri/system/system.py#L855

The assertion in the above line fails. However, I think the current implementation (PR #308) will pass the assertion since the off-diagonal translation invariance is imposed (i.e. the phase factor is multiplied) after `do_ws_dist()`.

**Comment by scarpoz** [comment]
Dear Seung-Ju, 

The reason why `do_ws_dist()` is performed before is because the recentered matrices require phase factors that depend on the lattice vectors R. Since such vectors are modified with `do_ws_dist()`, one calls this function first to have the final list of R vectors. Otherwise, if `use_ws = True` then these phase factors would be wrong.

**Comment by sjhong6230** [comment]
> Dear Seung-Ju,
> 
> The reason why `do_ws_dist()` is performed before is because the recentered matrices require phase factors that depend on the lattice vectors R. Since such vectors are modified with `do_ws_dist()`, one calls this function first to have the final list of R vectors. Otherwise, if `use_ws = True` then these phase factors would be wrong.
> 
> Hope it helps!
> 
> Best, Óscar

Thanks! Now I understood the reason. I think we can close this issue.
