### ISSUE TITLE
Error using pythtb interface

### ISSUE THREAD

**Issue by apezol** [wannier-berri/wannier-berri#322]
Dear developers,

I'm trying to use the example of the Kane-Mele model to calculate some transport quantities with Wannierberri, but I'm receiving the following message:

ValueError: non-broadcastable output operand with shape (1,1) doesn't match the broadcast shape (2,2)

which might be coming from this:

Ham_R[i, j, iR] += nhop[0]

since the hoppings are defined as matrices when taking the sites as spinors.

I'm calling the system like this:

system=wberri.System_PythTB(my_model,spin=True)

I'd really appreciate if you can help me to solve this issue, do I need to add something when interfacing pythtb with wannierberri?,

best regards,

**Comment by apezol** [comment]
It was install using pip, should I try the other one?,

**Comment by stepan-tsirkin** [comment]
yes, there were some fixes recently regarding the pythtb spinful models. Those are not released to pip yet

**Comment by apezol** [comment]
Hi Stepan,

It seems to be working now, although integration is performed through 'run'  instead of 'integrate' as in the released version. Anyway, thanks a lot!.

**Comment by stepan-tsirkin** [comment]
'integrate' is not supported for a long time, it was just hanging there. So, now it is permanently removed. 'run' is more powerful, so, please use it.
