### ISSUE TITLE
ValueError: Invalid fortran file '/public/home/reduced_NB=60/wannier90.uHu

### ISSUE THREAD

**Issue by shishirkrpandey** [wannier-berri/wannier-berri#332]
Dear Dr. Stepan,
I am trying to calculate the orbital magnetization and berry curvature for CrTe system. The band structure has 60 bands from VASP calculations and I have a wannier90 TB (with ISYM = -1 no symmetry) with 32 (2* 5 of Cr and 3*2 of Te   X 2  with SOC). The WAVECAR (also with ISYM = -1) is first used to generate wannier90.spn file using your package with the command 

`python3 -m wannierberri.utils.vaspspn fin=WAVECAR NB=0 norm=none IBstart=1> log`

Then to generate wannier90.uHu file, I used the following command, 

`python3 -m wannierberri.utils.mmn2uHu wannier90  targets=uHu formatted=uHu> log_uHu`

Both of the files appear to be generated properly as the OK message appears at the end of their generation. However, when I use these files, following error message appears while reading the wannier90.uHu file during berri curvature calculation, 

> Traceback (most recent call last):
>   File "/public/home/software/miniconda3/lib/python3.8/site-packages/fortio.py", line 116, in _check_byteorder
>     self.goto_record(1)
>   File "/public/home/software/miniconda3/lib/python3.8/site-packages/fortio.py", line 230, in goto_record
>     self.skip_record(rec)
>   File "/public/home/software/miniconda3/lib/python3.8/site-packages/fortio.py", line 193, in skip_record
>     _assert_header_equal(head, tail)
>   File "/public/home/software/miniconda3/lib/python3.8/site-packages/fortio.py", line 36, in _assert_header_equal
>     raise ValueError("inconsistent record headers: %d != %d." % (head, tail))
> ValueError: inconsistent record headers: 544557173 != 825308212.
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/public/home/software/miniconda3/lib/python3.8/site-packages/fortio.py", line 120, in _check_byteorder
>     self.goto_record(1)
>   File "/public/home/software/miniconda3/lib/python3.8/site-packages/fortio.py", line 230, in goto_record
>     self.skip_record(rec)
>   File "/public/home/software/miniconda3/lib/python3.8/site-packages/fortio.py", line 193, in skip_record
>     _assert_header_equal(head, tail)
>   File "/public/home/software/miniconda3/lib/python3.8/site-packages/fortio.py", line 36, in _assert_header_equal
>     raise ValueError("inconsistent record headers: %d != %d." % (head, tail))
> ValueError: inconsistent record headers: 1967682848 != 825112120.
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/public/home/software/miniconda3/lib/python3.8/site-packages/wannierberri/__utility.py", line 39, in __init__
>     super().__init__(filename, mode='r', header_dtype='uint32', auto_endian=True, check_file=True)
>   File "/public/home/software/miniconda3/lib/python3.8/site-packages/fortio.py", line 91, in __init__
>     self._check_byteorder()
>   File "/public/home/software/miniconda3/lib/python3.8/site-packages/fortio.py", line 126, in _check_byteorder
>     raise ValueError("Invalid fortran file '%s'." % self.file)
> ValueError: Invalid fortran file '/public/home/crte/wan/clean/reduced_NB=60/wannier90.uHu'.
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/public/home/software/miniconda3/lib/python3.8/site-packages/fortio.py", line 116, in _check_byteorder
>     self.goto_record(1)
>   File "/public/home/software/miniconda3/lib/python3.8/site-packages/fortio.py", line 230, in goto_record
>     self.skip_record(rec)
>   File "/public/home/software/miniconda3/lib/python3.8/site-packages/fortio.py", line 184, in skip_record
>     _assert_header_abs_equal(head, tail)
>   File "/public/home/software/miniconda3/lib/python3.8/site-packages/fortio.py", line 41, in _assert_header_abs_equal
>     raise ValueError("inconsistent record headers: |%d| != |%d|." % (head, tail))
> ValueError: inconsistent record headers: |544557173| != |825308212|.
> 
> During handling of the above exception, another exception occurred:
> Traceback (most recent call last):
>   File "/public/home/software/miniconda3/lib/python3.8/site-packages/fortio.py", line 120, in _check_byteorder
>     self.goto_record(1)
>   File "/public/home/software/miniconda3/lib/python3.8/site-packages/fortio.py", line 230, in goto_record
>     self.skip_record(rec)
>   File "/public/home/software/miniconda3/lib/python3.8/site-packages/fortio.py", line 184, in skip_record
>     _assert_header_abs_equal(head, tail)
>   File "/public/home/software/miniconda3/lib/python3.8/site-packages/fortio.py", line 41, in _assert_header_abs_equal
>     raise ValueError("inconsistent record headers: |%d| != |%d|." % (head, tail))
> ValueError: inconsistent record headers: |1967682848| != |825112120|.
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "morb_contr.py", line 31, in <module>
>     system=wberri.System_w90(seedname='wannier90',berry=True,morb=True,spin=True, guiding_centers = True)
>   File "/public/home/software/miniconda3/lib/python3.8/site-packages/wannierberri/system/system_w90.py", line 134, in __init__
>     uhu = UHU(seedname)
>   File "/public/home/software/miniconda3/lib/python3.8/site-packages/wannierberri/system/__w90_files.py", line 422, in __init__
>   super().__init__(seedname=seedname, formatted=formatted, suffix='uHu')
>   File "/public/home/software/miniconda3/lib/python3.8/site-packages/wannierberri/system/__w90_files.py", line 395, in __init__
>     f_uXu_in = FortranFileR(seedname + "." + suffix)
>   File "/public/home/software/miniconda3/lib/python3.8/site-packages/wannierberri/__utility.py", line 42, in __init__
>     super().__init__(filename, mode='r', header_dtype='int32', auto_endian=True, check_file=True)
>   File "/public/home/software/miniconda3/lib/python3.8/site-packages/fortio.py", line 91, in __init__
>     self._check_byteorder()
>   File "/public/home/software/miniconda3/lib/python3.8/site-packages/fortio.py", line 126, in _check_byteorder
>     raise ValueError("Invalid fortran file '%s'." % self.file)
> ValueError: Invalid fortran file '/public/home/crte/wan/clean/reduced_NB=60/wannier90.uHu'.

May I request you to please let me know where I am making a mistake and how to resolve this issue? My system is metallic.  
Thank you in advance.

**Comment by stepan-tsirkin** [comment]
I think the issue is that by default WannierBerri expects uHu to be unformatted (therefore the FortranFile object is used)

either generate it as unformatted, or force it to read as formatted, 

It is not well documented, but I guess you should pass

```
System_w90(... , formatted = ('uHu',) ) 
````

See the following lines of the code here:

https://github.com/wannier-berri/wannier-berri/blob/5bfe6bd4151fa52656fb357616936aa4b290dcb5/wannierberri/system/system_w90.py#L80

https://github.com/wannier-berri/wannier-berri/blob/5bfe6bd4151fa52656fb357616936aa4b290dcb5/wannierberri/system/system_w90.py#L116-L119

https://github.com/wannier-berri/wannier-berri/blob/5bfe6bd4151fa52656fb357616936aa4b290dcb5/wannierberri/system/w90_files.py#L324-L351
