### ISSUE TITLE
Reproducing postw90 Fe Berry curvature by Wannierberri

### ISSUE THREAD

**Issue by Vahid999** [wannier-berri/wannier-berri#337]
I have calculated the Total Berry curvature of bcc Fe (Example 18 in Wannier90 package) as attached and the result agrees with Fig.2 of PRL92, 037204 (2004). Then I use the following script to get the same result from Wannierberri (also attached) but the Berry curvature is different from the one by postw90.  Here is the script:

`import wannierberri as wberri
import pyfftw
import numpy as np
import pickle
from numpy import savetxt

parallel = wberri.Parallel(num_cpus=40, progress_step_percent=10)

calculators = {}

system=wberri.System_w90('Fe',berry=True, guiding_centers=True, fft='numpy')

path=wberri.Path(system,
                 k_nodes=[
        [0.0000, 0.0000, 0.0000],   #  G
        [0.5000 ,-0.5000, -0.5000],   #  H
        [0.75000, 0.25000, -0.2500],   #  P
        [0.5000, 0.0000, -0.5000],   #  N
        [0.0000, 0.0000, 0.0000 ]  , #  G
        [0.5000 ,-0.5000, -0.5000],   #  H
        [0.5000, 0.0000, -0.5000],   #  N
        [0.0000, 0.0000, 0.0000 ]  , #  G
        [0.75000, 0.25000, -0.2500],   #  P
        [0.5000, 0.0000, -0.5000] ] ,   #  N
                 labels=["G","H","P","N","G","H","N","G","P","N"],
                 length=500 ) 

efermi=12.6284

tabulators = { "Energy": wberri.calculators.tabulate.Energy(),
               "berry" : wberri.calculators.tabulate.BerryCurvature(),
             }

tab_all_path = wberri.calculators.TabulatorAll(
                    tabulators,
                    ibands = np.arange(1,18),
                    mode = "path"
                        )

result=wberri.run(system,
                  grid=path,
                  calculators = {"tabulate" : tab_all_path},
                  parallel = parallel,
                  parameters_K = dict( fftlib = "numpy" ),
                  print_Kpoints = False)

print (result.results)
path_result = result.results["tabulate"]
pickle.dump(path_result,open("path_berry.pickle","wb"))

k=path.getKline()

curvz=path_result.get_data(quantity='berry',iband=np.arange(16),component="z")
curvy=path_result.get_data(quantity='berry',iband=np.arange(16),component="y")
curvx=path_result.get_data(quantity='berry',iband=np.arange(16),component="x")

np.savetxt("curvx.dat", np.array(curvx))
np.savetxt("curvy.dat", np.array(curvy))
np.savetxt("curvz.dat", np.array(curvz))
np.savetxt("k.dat", np.array(k))`

I finally add all the Berry curvatures from all the bands to get the total Berry curvature for each direction.

Does anyone know what changes are needed in the script to reproduce the published Berry curvature?

Thank you,
Vahid

[postw90_Example18.pdf](https://github.com/user-attachments/files/15948137/postw90_Example18.pdf)
[wannierberri.pdf](https://github.com/user-attachments/files/15948140/wannierberri.pdf)

**Comment by stepan-tsirkin** [comment]
I think it is because of this line:

``` python
ibands = np.arange(1,18),
```

In python indices start with zero, so you are excluding the lowest band (indexed as 0)

**Comment by Vahid999** [comment]
I changed the index as you suggested and now the code is as shown below but the attached Berry curvature still is quite different from the published one for Fe. I have also attached the slurm output.

import wannierberri as wberri
import pyfftw
import numpy as np
import pickle
from numpy import savetxt

parallel = wberri.Parallel(num_cpus=40, progress_step_percent=10)

calculators = {}

system=wberri.System_w90('Fe',berry=True, guiding_centers=True, fft='numpy')

path=wberri.Path(system,
                 k_nodes=[
        [0.0000, 0.0000, 0.0000],   #  G
        [0.5000 ,-0.5000, -0.5000],   #  H
        [0.75000, 0.25000, -0.2500],   #  P
        [0.5000, 0.0000, -0.5000],   #  N
        [0.0000, 0.0000, 0.0000 ]  , #  G
        [0.5000 ,-0.5000, -0.5000],   #  H
        [0.5000, 0.0000, -0.5000],   #  N
        [0.0000, 0.0000, 0.0000 ]  , #  G
        [0.75000, 0.25000, -0.2500],   #  P
        [0.5000, 0.0000, -0.5000] ] ,   #  N
                 labels=["G","H","P","N","G","H","N","G","P","N"],
                 length=500 )

efermi=12.6284

tabulators = { "Energy": wberri.calculators.tabulate.Energy(),
               "berry" : wberri.calculators.tabulate.BerryCurvature(),
             }

tab_all_path = wberri.calculators.TabulatorAll(
                    tabulators,
                    ibands = np.arange(0,18),
                    mode = "path"
                        )

result=wberri.run(system,
                  grid=path,
                  calculators = {"tabulate" : tab_all_path},
                  parallel = parallel,
                  parameters_K = dict( fftlib = "numpy" ),
                  print_Kpoints = False)

print (result.results)
path_result = result.results["tabulate"]
pickle.dump(path_result,open("path_berry.pickle","wb"))
k=path.getKline()
curvz=path_result.get_data(quantity='berry',iband=np.arange(18),component="z")
curvy=path_result.get_data(quantity='berry',iband=np.arange(18),component="y")
curvx=path_result.get_data(quantity='berry',iband=np.arange(18),component="x")
np.savetxt("curvx.dat", np.array(curvx))
np.savetxt("curvy.dat", np.array(curvy))
np.savetxt("curvz.dat", np.array(curvz))
np.savetxt("k.dat", np.array(k)

Might there be another issue with my python script?

Thanks,
Vahid



On Jun 23, 2024, at 9:35 PM, Stepan Tsirkin ***@***.***> wrote:

CAUTION: The Sender of this email is not from within Dalhousie.


I think it is because of this line:

ibands = np.arange(1,18),

In python indices start with zero, so you are excluding the lowest band (indexed as 0)

**Comment by Vahid999** [comment]
I think the two attachments in my last post did not go through. Here they are.
[wannierberri.pdf](https://github.com/user-attachments/files/16087001/wannierberri.pdf)
[slurm-640010.txt](https://github.com/user-attachments/files/16087009/slurm-640010.txt)

**Comment by stepan-tsirkin** [comment]
Hi @Vahid999 ,

How do you add up the Berry curvatures? postw90 plots the BC of occupied bands, and occupation is a k-dependent quantity, so the curve on the plot has sharp steps where a band crosses the Fermi level. If you just add up the BC of all bands - you get almost a zero. Technically, the sum of BC of a complete set of states is always zero, but the set of Wannier Functions is not a complete set, so you may get something small. 

so, for each k-point you need to sum up only the occupied bands, based on the tabulated "Energy" quantity 

for benchmarking with postw90 there is a page https://docs.wannier-berri.org/en/master/benchmark.html
it is about integrated (over k) ahc, and it uses the old "integrate"function, but essentially it also gives some guidlines.

**Comment by Vahid999** [comment]
Hi Stepan,

You are right. I did add all the 18 Berry curvatures for each band. I see my error now. For each k-point along the path, I should add only the bands that are below E_F.

I am very grateful for your guidance.

Best,
Vahid


On Jul 3, 2024, at 12:44 PM, Stepan Tsirkin ***@***.***> wrote:

CAUTION: The Sender of this email is not from within Dalhousie.


Hi @Vahid999<https://github.com/Vahid999> ,

How do you add up the Berry curvatures? postw90 plots the BC of occupied bands, and occupation is a k-dependent quantity, so the curve on the plot has sharp steps where a band crosses the Fermi level. If you just add up the BC of all bands - you get almost a zero. Technically, the sum of BC of a complete set of states is always zero, but the set of Wannier Functions is not a complete set, so you may get something small.

so, for each k-point you need to sum up only the occupied bands, based on the tabulated "Energy" quantity

for benchmarking with postw90 there is a page https://docs.wannier-berri.org/en/master/benchmark.html
it is about integrated (over k) ahc, and it uses the old "integrate"function, but essentially it also gives some guidlines.
