### ISSUE TITLE
 adding C3v symmetry in  system.set_symmetry() error

### ISSUE THREAD

**Issue by SaranshaM** [wannier-berri/wannier-berri#348]
Respected Sir,

I was evaluating BCD for system 1H-MoS2 monolayer. As per the literature, the BCD should be zero for system having C3v symmetry. When i add C3v symmetry in  system.set_symmetry(["TimeReversal", "C3v" ]), it gives an error of The symmetry C3v could not be recognized. 
As i looked into the https://docs.wannier-berri.org/en/latest/docs/symmetries.html, i found that the C3v is not implemented. Sir, is there way to add the above C3v symmetry operations for calculation of such materials.  Since C3 rotation is present in C3z, can we write C3z*Mx and so on for C3v to be used in system.set_symmetry().

I sincerely appreciate your kind assistance.
Best regards

**Comment by stepan-tsirkin** [comment]
`System.set_symmetry` expects a list of symmetry operations - generators of the group. 

C3v is not a symmetry operation, it is a point group name, which has generators C3z and Mx (or My, depending how you put your axes).

So the correct way will be 
```python
 system.set_symmetry(["TimeReversal", "C3z", "Mx"])
```
