### ISSUE TITLE
The question about the "smearEf" parameter when calculating AHC.

### ISSUE THREAD

**Issue by xiuxianYang** [wannier-berri/wannier-berri#349]
Hi，
When I calculate the variation of AHC with energy, the AHC curve has many spikes. I want to use the "smearEF" parameter, but changing the value of "smearEF" does not affect the AHC results at all.

How can I apply a broadening to AHC?

Thanks.

Xiuxian

**Comment by xiuxianYang** [comment]
Thank you very much for replying to my issue.

The wannierberry version is "wannierberri-0.17.0", that is the latest version.

Here is my python code:
###############################################################
import pyfftw
import numpy as np
import wannierberri as wberri
import os
os.environ['OPENBLAS_NUM_THREADS'] = '1'
os.environ['MKL_NUM_THREADS'] = '1'
os.environ['OMP_NUM_THREADS'] = '1'

system=wberri.System_w90('wannier90',berry=True)
grid=wberri.Grid(system,length=4000)
num_proc = 96
parallel=wberri.Parallel(num_cpus=num_proc)
Efermi=np.linspace(5.8555, 6.8555, 101)
smearEf=30 # 10K ~~ 1meV
wberri.run(system,
            grid=grid,
            calculators = {
                "ahc":wberri.calculators.static.AHC(Efermi=Efermi,tetra=False)
                          },
            parallel=parallel,
            adpt_num_iter=10,
            fout_name='wannier',
            suffix = "run",
            restart=False,
            )

parallel.shutdown()
############################################################

**Comment by stepan-tsirkin** [comment]
@xiuxianYang , in your script you define a variable smearEf, but you never use it. How do you expect it to affect anything? 

Please, see  #305 , in particular https://github.com/wannier-berri/wannier-berri/issues/305#issuecomment-2150225221

how to use smearing

**Comment by xiuxianYang** [comment]
Hi,
I tried adding smoother to the calculators to make the AHC curve smoother. Is this effective?
##############################################################
import pyfftw
import numpy as np
import wannierberri as wberri
import os
os.environ['OPENBLAS_NUM_THREADS'] = '1'
os.environ['MKL_NUM_THREADS'] = '1'
os.environ['OMP_NUM_THREADS'] = '1'
system=wberri.System_w90('wannier90',berry=True)
grid=wberri.Grid(system,length=201)
num_proc = 64
parallel=wberri.Parallel(num_cpus=num_proc)
Efermi=np.linspace(5.1370, 6.1370 ,101)
smoother = wberri.get_smoother(Efermi, 200, "Fermi-Dirac")
wberri.run(system,
            grid=grid,
            calculators = {
                "ahc":wberri.calculators.static.AHC(Efermi=Efermi,smoother = smoother, tetra=False)
                          },
            parallel=parallel,
            adpt_num_iter=10,
            fout_name='Fe',
            suffix = "run",
            restart=False,
            )

parallel.shutdown()
#########################################################
