### ISSUE TITLE
Feature Requests: Spin Berry curvature contribution to the SHC

### ISSUE THREAD

**Issue by trumanmiguel** [wannier-berri/wannier-berri#35]
Hi @stepan-tsirkin, 

I would like to make 2 feature requests. It'd be great to calculate the spin Berry curvature contributions to the SHC just like the bands+shc task in the kpath module and the shc+fermi_lines task in the kslice module in Wannier90. I'd appreciate it as it's helpful when analysing the results. 

Thanks. 

Regards, 
Truman

**Comment by stepan-tsirkin** [comment]
@jaemolihm, @manxkim , After merging of #85  would it be easy to add spin berry curvature to `tabulate()`  quantities?

**Comment by jaemolihm** [comment]
Yes. I have one problem: how can I pass an additional parameter to `frml.SpinOmega` (which is a calculator)? I need to pass `spin_current_type`. Setting `parameters = {"spin_berry": {"spin_current_type": "ryoo"}}` does not work. Specifically, I cannot understand the logic of the following code.

https://github.com/wannier-berri/wannier-berri/blob/a0d8e41e2a215e7f5c845f342d319f876961461f/wannierberri/__tabulate.py#L78-L87

**Comment by stepan-tsirkin** [comment]
@jaemolihm 

If yuo make it a built-in function, you need to define `additional_parameters`, like here:

https://github.com/wannier-berri/wannier-berri/blob/a0d8e41e2a215e7f5c845f342d319f876961461f/wannierberri/__tabulate.py#L60-L63

like 
```
additional_parameters['SpinOmega']['spin_current_type']='ryoo'
```
The idea behind this code is that you can use the same formula with different parameters in the same calculation. 

like  [here](https://wannier-berri.org/docs/parameters.html)
So, string before the first '^' symbol denotes the name of the quantity as defined in `__tabulate.py` , and the rest is a comment to distinguish calculations. 

Doe this explanation makes it more clear?

**Comment by jaemolihm** [comment]
I see. Thank you very much for the explanation. The ^ thing is really nice! (I hadn’t understand what “ same quantity with different parameters in one run” until now 😂 ) I will make a PR on spin Berry tabulation soon.

**Comment by stepan-tsirkin** [comment]
Ok, that means we need a better explanation in the documentation. You may try to add your words there.

**Comment by jaemolihm** [comment]
Hi @trumanmiguel , sorry for taking so long, but we now have the functionality to tabulate spin Berry curvature. You can use like the following. (The `path` can be set using `wberri.Path`, see https://github.com/wannier-berri/wannier-berri/blob/f80d8fa4ad7819c8d31396273a45e1c7946ea334/tests/test_path.py)
```python3
path_result = wberri.tabulate(system, grid=path,
                              quantities=["spin", "spin_berry^ryoo", "spin_berry^qiao"],
                              specific_parameters = {'spin_berry^ryoo': {'spin_current_type': 'ryoo'},
                                                     'spin_berry^qiao': {'spin_current_type': 'qiao'}},
                             )
```

Note that WannierBerri prints out the k-point and band-resolved spin Berry curvature, while Wannier90 gives k-point resolved but band-summed one.

Please let us know if you have any comments or issues using this feature.

**Comment by trumanmiguel** [comment]
Hi Jae-Mo,

Thanks for developing the code to tabulate the spin Berry curvature. I appreciate it.

Regards,
Truman
