### ISSUE TITLE
Error reading wannier90_tb.dat file

### ISSUE THREAD

**Issue by supratik1289** [wannier-berri/wannier-berri#357]
I am trying to setup a system from TB model built using wannier90 and I am getting this error can anyone help:
![image](https://github.com/user-attachments/assets/2d8a2d39-9d15-446c-bbf5-004f90cceeba)

**Comment by supratik1289** [comment]
This is wannier berri version 1.0.1 installed using pip install wannierberri[all]

**Comment by stepan-tsirkin** [comment]
looks like a bug

**Comment by stepan-tsirkin** [comment]
I think I see where it comes from. in System_tb the wannier centers are determined from the AA matrix, but if berry=False, the AA matrix is not read:

https://github.com/wannier-berri/wannier-berri/blob/9e20c3461e167b12feea4abfdc42c8471296494f/wannierberri/system/system_tb.py#L75-L85

try to use System_tb( ... , berry=True) even if you do not need the berry curvature.  I think it would work. 

I will do a proper fix later, but so far that should work.

**Comment by stepan-tsirkin** [comment]
@supratik1289 

The issue should be fixed in v1.0.2
Could you update and check?

**Comment by supratik1289** [comment]
> I think I see where it comes from. in System_tb the wannier centers are determined from the AA matrix, but if berry=False, the AA matrix is not read:
> 
> https://github.com/wannier-berri/wannier-berri/blob/9e20c3461e167b12feea4abfdc42c8471296494f/wannierberri/system/system_tb.py#L75-L85
> 
> try to use System_tb( ... , berry=True) even if you do not need the berry curvature. I think it would work.
> 
> I will do a proper fix later, but so far that should work.

Thanks, it works now
