### ISSUE TITLE
Which part of the conductivity is the output file in the optical conductivity calculation?

### ISSUE THREAD

**Issue by sfqian** [wannier-berri/wannier-berri#365]
The optical conductivity in postw90 has two part, the symmetric conductivity and antisymmetric conductivity. which part of the conductivity is the output file of wannierberri?

**Comment by stepan-tsirkin** [comment]
the calculator [OpticalConductivity](https://github.com/wannier-berri/wannier-berri/blob/d11e19e99eae6744801a0e345a8014d713e62ac0/wannierberri/calculators/dynamic.py#L198-L210) calculates the full tensor. From that you may extract the (anti)symmetric or (anit)hermitian part, or whatever you want

**Comment by sfqian** [comment]
Sorry, I still confuse about the tensor of calculator [OpticalConductivity]. Take σ_xy as an example, the output of postw90 has wannier90-kubo_A_xy.dat and wannier90-kubo_S_xy.dat, which represent the antisymmetric and symmetric conductivity,  while the output file of wannierberri has only one column of σ_xy (Two columns of σ_xy ​​but they are all the same.).

**Comment by stepan-tsirkin** [comment]
to get the symmetric component you need $(\sigma_{xy}-\sigma_{yx})/2$ , for the symmetric one $(\sigma_{xy}+\sigma_{yx})/2$

**Comment by sfqian** [comment]
I see. Thank you so much.
