### ISSUE TITLE
Inconsistency in reading UXU

### ISSUE THREAD

**Issue by jaemolihm** [wannier-berri/wannier-berri#39]
There seems to be an inconsistency in reading the unformatted and formatted UXU files.

I generated an unformatted and a formatted uHu file from the same wavefunctions. And then I read them using `class UXU`. Below is the result. The two UXU data becomes identical only after swapping two nnb indices.

```
>>> import numpy as np
>>> from wannierberri.__w90_files import UXU
>>> a = UXU("Fe")
----------
  uHu   
---------
formatted == False
using fortio to read
reading Fe.uHu : <Created on  2Apr2021 at 18:17:33>
----------
 uHu OK  
---------

>>> b = UXU("Fe_formatted", formatted=True)
----------
  uHu   
---------
formatted == True
reading Fe_formatted.uHu : <Created on  2Apr2021 at 18:17:11>
----------
 uHu OK  
---------

>>> np.linalg.norm(a.data - b.data)
6981.984517351669
>>> np.linalg.norm(np.swapaxes(a.data, 1, 2) - b.data)
7.742781712282713e-08
```

Maybe the last line of the following code should be `self.data[ik,ib2,ib1]`, not `self.data[ik,ib1,ib2]`?
https://github.com/stepan-tsirkin/wannier-berri/blob/4bd29e4a40b4d2fa6da5e2c7ba11947c2d9c8649/wannierberri/__w90_files.py#L381-L386

**Comment by stepan-tsirkin** [comment]
Thanks for spotting this. So, you think it is the unformatred file that is incorrect? I will recheck it. 

Your files are from pe2wannier, right. Curious, if the mmn2uHu has the same problem?


Another question, if this issue affects the result for orbital magnetization. Probably it does not, but for evaluation of the nonabelian orbital moment matrix it may affect.

**Comment by jaemolihm** [comment]
In the above, I used pw2wannier90. I confirm that the same problem occurs for uHu generated using mmn2uHu.

**Comment by jaemolihm** [comment]
I looked into `pw2wannier90`, and it is coded a bit strangely.
If one reads all data in uHu file in Fortran (column-major) order, we get `uHu_pw2wan(n, m, ib1, ib2, ik) = <u_{k+b1, m}|H|u_{k+b2, n}>`.

In `postw90.x`, there is a line taking the transpose so that the read array becomes `uHu_postw90(m, n, ib1, ib2, ik) = <u_{k+b1, m}|H|u_{k+b2, n}>`.
```fortran
! pw2wannier90 is coded a bit strangely, so here we take the transpose
Ho_qb1_q_qb2 = transpose(Ho_qb1_q_qb2)
```

In `UXU` of `wannierberri`, the formatted and unformatted versions behave differently. (Both are converted to Python row major order.)
- formatted:
    `uHu_formatted(ik, ib2, ib1, m, n) = uHu_pw2wan(n, m, ib1, ib2, ik) = <u_{k+b1, m}|H|u_{k+b2, n}>`.
- unformatted:
    `uHu_unformatted(ik, ib1, ib2, m, n) = uHu_pw2wan(n, m, ib1, ib2, ik) = <u_{k+b1, m}|H|u_{k+b2, n}>`.

Which one (if any) is correct will depend on other parts of code using `uHu`, so I am not sure. If you confirm that one of the two is correct, I can create a Merge request.

Still, even if the unformatted version turns out to be correct, I would change ib1 and ib2 as well as m and n to make the labels consistent with pw2wannier90.

**Comment by stepan-tsirkin** [comment]
Thanks for checking this carefully.  Regardless of what is done later in the code (which I will recheck again), to avoid any confusions it should be 
`uHu(ik, ib1, ib2, m, n) =  <u_{k+b1, m}|H|u_{k+b2, n}>`
it totally makes sense, when the order of indices is the same in the equation and in the array.  In that sense, the unformatted read is correct, right? And I  did  the benchmarks against postw90 , so the results matched. (I tested with unformatted only)

 Therefore, I think we should only change the formatted one, with a `.swapaxes(1,2)` and that's it. Could you make such a PR.  Or can you justify more why you think 

> Still, even if the unformatted version turns out to be correct, I would change ib1 and ib2 as well as m and n to make the labels consistent with pw2wannier90.

I do not really understand that.

Can you double-check if the other arrays (MMN, SHU, SIU, etc) also follow this convention, namely: 

`MMN.data[ik,ib,m,n] = <u_{m}|u_{k+b, n}>`   

The convention of pw2wannier90 is weird, but it is established, and it looks dangerous to change it now, right?

what is really confusingly coded is mmn2uHu:

https://github.com/wannier-berri/wannier-berri/blob/ff1682b50b1a28b5e9ecfd6981e75873e65c79c8/wannierberri/mmn2uHu.py#L230-L243

I believe that it is correct (because the results matched to the pw2wannier90.x for large NBsum), but I guess it uses multiple times the interchanges between m,n and ib1,ib2 . and also does not transpose the reas on mmn. But I am still confused to understand why it is correct. That script is older than WannierBerri.   Now, I would rewrite it by using the classes in __w90_files.py and implementing transformations between them, e.g. MMN, EIG -> UHU, reductions of bands and writing to files. But that's a bit more work to do.

**Comment by stepan-tsirkin** [comment]
Let's check, in the mmn2uHu, the  MMN is read as written:
https://github.com/wannier-berri/wannier-berri/blob/ff1682b50b1a28b5e9ecfd6981e75873e65c79c8/wannierberri/mmn2uHu.py#L118-L120

Therefore `MMN[ik][ib][[m,n]=<u_{n,k}|u_{m,k+b}> `

then : 

https://github.com/wannier-berri/wannier-berri/blob/ff1682b50b1a28b5e9ecfd6981e75873e65c79c8/wannierberri/mmn2uHu.py#L232-L233

`A[ib2,ib1,m,n] =  <u_{k+b1, m}|H|u_{k+b2, n}>`

Then we linearise it in C-order : 
https://github.com/wannier-berri/wannier-berri/blob/ff1682b50b1a28b5e9ecfd6981e75873e65c79c8/wannierberri/mmn2uHu.py#L238-L243
But in  pw2wannier it is assumed as F-order,  so it is equivalent to: 
`uHu_pw2wan(n, m, ib1, ib2, ik) = <u_{k+b1, m}|H|u_{k+b2, n}> `
like it should be.

Is that right?

**Comment by jaemolihm** [comment]
> Regardless of what is done later in the code (which I will recheck again), to avoid any confusions it should be uHu(ik, ib1, ib2, m, n) = <u_{k+b1, m}|H|u_{k+b2, n}> it totally makes sense, when the order of indices is the same in the equation and in the array. In that sense, the unformatted read is correct, right?

Yes, exactly.

> Still, even if the unformatted version turns out to be correct, I would change ib1 and ib2 as well as m and n to make the labels consistent with pw2wannier90.

What I meant in this quote is that in `pw2wannier90.f90`, the faster index is `ib1`, while it is `ib2` in WannierBerri (the unformatted one):
```python3
self.data[ik,ib1,ib2]=tmp[:,:,0]+1j*tmp[:,:,1]
```
So I thought it would be better to change `ib1` to `ib2` and vice versa in WannierBerri. Then, to make the result correct, we also need to swap `m` and `n`.

>The convention of pw2wannier90 is weird, but it is established, and it looks dangerous to change it now, right?

Yes, I think so.

> Can you double-check if the other arrays (MMN, SHU, SIU, etc) also follow this convention, namely:

But sHU and sIu shares the same issue with uHu and uIu. They share the same convention as uHu (i.e. F-order but additional transpose). But it seems that in WannierBerri, only the unformatted version is implemented, which is correct.

Other than that, I think there is no problem. For example, MMN is implemented in a non-weird way in pw2wannier90: `MMN(m,n,ib,ik)=<u_{k,m}|u_{k+b,n}>`. In WannierBerri, there is a transpose, so the result is correct: `MMN.data[ik,ib,m,n] = <u_{k,m}|u_{k+b, n}>`.
```python3
self.data=np.array(data).reshape(self.NK,self.NNB,self.NB,self.NB).transpose((0,1,3,2))
```

**Comment by jaemolihm** [comment]
Also, I agree on your analysis of `mmn2uHu`. So in short, in `mmn2uHu` it is just C order, and in `pw2wannier90`, it is (F order + transpose) = C order. Hence, they are consistent.

>Now, I would rewrite it by using the classes in __w90_files.py and implementing transformations between them, e.g. MMN, EIG -> UHU, reductions of bands and writing to files. But that's a bit more work to do.

But I agree this would be better in the long run.

**Comment by stepan-tsirkin** [comment]
> The faster index in the for loop is `ib1`, but the faster index in the array is `ib2`. So I thought it would be better to swap `ib1` and `ib2` in the last line of this quote. Then, to make the result correct, we also need to swap `m` and `n` (i.e. change `transpose(2,1,0)` to `transpose(2,0,1)`).

I do not think it makes much sense to speak about "faster index" in numpy array, as they may be stored internally in different ordering, also discontinuous. 

> Maybe to the code more readable, we could read all arrays assuming F-order, and after reading everything take the transpose.

Probably you are right here, you may do this in a PR.

> sHu and sIu share the same issue with uHu and uIu, because they share the same convention as uHu in pw2wannier90 (i.e. F-order but additional transpose). Currently, it seems that in WannierBerri, only the unformatted version is implemented, which is correct.

Actually, also for uHu and spn, although the formatted reading is implemented, there is no flag in "System_w90" to tell the code to read them as formatted. Should we try to do automated detection, e.g. by 

```
try : 
    # read as (un)formatted
except:
   # do the other way.
```
