### ISSUE TITLE
Python version requirement

### ISSUE THREAD

**Issue by jaemolihm** [wannier-berri/wannier-berri#54]
Is there any requirement on the python version?

I propose to require python version >= 3.6, for several reasons:
* Python 3.5 has reached its end of life in 13 Sep 2020 : https://endoflife.date/python.
* Ray seems to support python version >= 3.6 only.
* If we decide to support only versions >= 3.6, then we can use new features such as fstrings (https://realpython.com/python-f-strings/) that are introduced in 3.6.

If we make a decision, we should set the `python_requires` argument in setup.py. https://packaging.python.org/guides/distributing-packages-using-setuptools/#python-requires

**Comment by stepan-tsirkin** [comment]
There is currently no requirement set, but of course with that number of packages included we cannot guarantee that WannierBerri will work with any of the old python3 versions.  Setting requirement for python >=3.6 is reasonable. 

Thanks for pointing to f-strings, that is nice. If you discover some other useful features that are available in newer versions of python, let us know, we may even raise the requirement for python version.

**Comment by stepan-tsirkin** [comment]
addressed in #69
