### ISSUE TITLE
merge vs squash-merge

### ISSUE THREAD

**Issue by stepan-tsirkin** [wannier-berri/wannier-berri#60]
what do you think, is it better to just merge, or squash commits before merge? 

My impression is that squash merge works badly in the following situation:
1) imagine, we have branch A that became a PR
2) meanwhile, commits of A are merged into B
3) than we add a few more commits to A, and finally squash-merge it into master
4) now I merge master into B and get an awful number of conflicts. 

Is it really because of squash? should we avoid it (at the cost of having ~50 mini commits per PR)

What is a better practice to proceed here?

**Comment by jaemolihm** [comment]
Yes, by using squash merge, one gets more merge conflicts. I think one should avoid squash merging except when there is a really good reason to do so.

Having many mini commits can be avoided by locally squashing commits using `git rebase` or `git commit --amend` before pushing to remote branch. For example,

1. Add a single feature via commits A1 and A2 (also with some bugs)
2. `git rebase -i HEAD~2` to squash commits A1 and A2 into A
3. Run test locally, test fails
4. Fix bugs, `git add`, and modify commit A via `git commit --amend`
5. Push to remote. We have a single commit in the history.

A good practice is that each commit should not break tests (at least locally). If test fails locally, fix them, and squash bugfix commits to the relevant commit (via `git rebase` or `git commit --amend`).
