### ISSUE TITLE
Add documentation and tests for all features

### ISSUE THREAD

**Issue by jaemolihm** [wannier-berri/wannier-berri#62]
This is a list of undocumented and/or untested features. If there are something more to add, please write in the reply and I will add them.

### Documentation
- [ ] shift current
- [ ] tildeD
- [ ] use_wcc_phase
- [ ] parameters_optical
- [ ] kBT vs smearEf in kubo
- [ ] Smoothers
- [ ] Results (unsmoothed & smoothed)
- [ ] AHE indices

### Tests

- [x] shift current (#65)
- [ ] tildeD
- [x] tabulate (#64)
- [ ] shc_alpha, beta, gamma
- [ ] tab_plot.py
- [ ] SHC + wcc
- [ ] shift current + wcc
- [x] orbital magnetization (#64)
- [ ] adaptive smearing in kubo

**Comment by stepan-tsirkin** [comment]
I think we can add tests for `tab_plot.py` For that we can modify them a bit, so that along with saving a figure, the routine will return the data that it actually plots, as arrays. And those bata will be benchmarked.

**Comment by jaemolihm** [comment]
Added "Results (unsmoothed & smoothed)" and "AHE indices", which were discussed in the mailing list by Truman Ng Yu.
https://physik.lists.uzh.ch/sympa/arc/wannier-berri/2021-08/msg00002.html
