### ISSUE TITLE
use_wcc_phase for orbital magnetization and spin Hall

### ISSUE THREAD

**Issue by jaemolihm** [wannier-berri/wannier-berri#63]
#45 introduced the use_wcc_phase option, which enables Berry curvature dipole (and some other) calculation with the so-called "tight-binding convention" (`use_wcc_phase=True`).

I tested spin Hall conductivity, and `use_wcc_phase=True` gave different results compared to `use_wcc_phase=False`, probably because <0m|Sr|Rn> and <0m|SHr|Rn> need some special treatment (their own `flag` in `_R_to_k_H`).
I guess similar problem exists in the orbital magnetization (but I have not tested this), because BB_R (<0m|H(r-R)|Rn>) and CC_R (<0m|rH(r-R)|Rn>) need special treatment (their own `flag`). Is this correct?

There are several `flag`s in `Data_K`, e.g. `flag='VV'`, but only `flag='AA'` is implemented. If they are not needed, we should delete them. If they are needed but not implemented, we should raise a `NotImplementedError` in `_R_to_k_H` until we get it fixed.

Also, I wonder what `flag` does can be done at the `system` level. (I remember this was discussed somewhere in #45.) If this can be done, tight-binding calculations can be faster because `AA_R` would be zero. @Liu-Xiaoxiong, are you working on this?

I'll try to implement `use_wcc_phase=True` for the spin Hall calculation.

@Liu-Xiaoxiong @stepan-tsirkin

**Comment by stepan-tsirkin** [comment]
Yes, every matrix element should be treated carefully. Xiaoxiong is working on that for the orbital moment. 

One thing that I do not really like about use_wcc_phase, is that it is a parameter of the system. While it shopuld be a parameter of the calculation. So, to change the parameter, we change the system, which is not logical. Instead, we may make a list of general parameters of the calculation, and pass them to integrate() and tabulate( ) as a dictionary, which further may be passed to the Data_K.__init__(). 

Just, I want that a system can be initialized only once, then pickled (or JSON'ed, as you like) and then used for multiple calculations. In particular, the tests will run faster then.

This also applies to other parameters, like `transl_inv`, and some others.

For example, symmetries should be a property of the system, but to use them or not - should be a parameter of the calculation.

**Comment by jaemolihm** [comment]
> Just, I want that a system can be initialized only once, then pickled (or JSON'ed, as you like) and then used for multiple calculations. In particular, the tests will run faster then.

If what you said is done, then pickle will not be needed to reuse system in tests. Fixtures will be sufficient. I agree that pickle is useful when running multiple calculations manually.

**Comment by stepan-tsirkin** [comment]
in #308 use_wcc_phase is implemented in a general way, without need for doing explicit conversions between conventions
