### ISSUE TITLE
BUG:  System_w90 works wrong with non-gamma-centered grids

### ISSUE THREAD

**Issue by stepan-tsirkin** [wannier-berri/wannier-berri#66]
As follows from the thread with Rafael Gonzalez 
https://physik.lists.uzh.ch/sympa/arc/wannier-berri/2021-06/msg00008.html

When an even Monkhorst-Pack grid is used (which does not include Gamma point),  the FFT in the construction of System_w90 goes wrong. With Gamma-centered grid it is fine. We need do find and fix the bug.

**Comment by Liu-Xiaoxiong** [comment]
Only even goes wrong? Do you ever try odd grid?

**Comment by stepan-tsirkin** [comment]
Odd MP grid (when all 3 numbers are odd) contains Gamma Point, so it will work. 

However now I am thinking if it is at all correct to use no-Gamma grids for Wannier functions. Maybe we should just through an error if Gamma point is not onthe grid.

In particular, the Hamiltonian is not periodic in R space with period N (size of the k-grid), it becomes H(R+N) = -H(R), while MDRS explicitly assumes H(R+N) = H(R). 

Although Wannier90 works somehow in that case, I am not sure it is fully correct. But all examples of Wannier90 use Gamma-centered grids.

Let's first explicitly disallow use of no-Gamma grids in the constructor of CHK, by checking the kpt_latt array. Xiaoxiong, could you do it?

**Comment by stepan-tsirkin** [comment]
fixed in #68
