### ISSUE TITLE
Combining kubo + fermiocean into one

### ISSUE THREAD

**Issue by manxkim** [wannier-berri/wannier-berri#84]
Wannierberri provides integrating quantities via `kubo` and `fermiocean`. The former is for optical quantites with frequency scan and fermi-energy scan at the same time, while the latter is only for fermi-energy scan.

I am thinking of combing `kubo` and `fermiocean` into one. For instance @jaemolihm implemented SHC(qiao and ryoo) into fermiocean which had been in kubo, see [`formula_shc`](https://github.com/jaemolihm/wannier-berri/tree/formula_shc/wannierberri) and (#67). As a result there are repetitive formulae in fermiocean(formula, covariant_formula, ... etc) and kubo. For the future development, the unification may not cause additional work. Every time some functions(external/internal terms, tetrahedron method, test sets, etc) are included one should make tests for whether two codes give the same result.

To do a freqscan, one may add a parameter `freqscan = True`. Some formulae will have omega, which can be an array. Others may not allow `freqscan`. Delta functions like `\delta(\epsilon_n - \epsilon_m - \hbar\omega)` in `kubo` will be still calculated using smearing.

Just in case `kubo` may be left for what is not expressed in terms of a fermiocean quantity.

**Comment by stepan-tsirkin** [comment]
@manxkim , the plan is to substitute the old kubo module by a new, based on FermiOcean and Formula_ln clases. (in which  Just I did not have time for that, hope you and @jaemolihm  will manage. Jae-Mo, waht is the status of that branch that you had? can it be turned into a PR now, after the fermiocean developments are merged into master?

Also, it will be great if you employ tetrahedron method both for Efermi and frequency scan.

Regarding the structure, at the moment the Formula_ln classes return only the matrices (matrix elements) that do not depend on the Efermi. The Fermi scan is done inside the FermiOcean, and depends on which  distribution function is used. I think, it would be optimal to do similar for optical, just the scan will be over Efermi and Omega. The difference is that in that case the matrix eleents will be labeled not by one, but by 2 energies.

One note, which so far is probably  not documented anywhere. The meaning of .nn and .ln methods. The formalism (that we are writing into a paper with @ivosouza0 ) assumes that all states are divided into "inner" and "outer" states. As "inner" we take either all occupied states (for the Fermisea quantities) or a group of degenerate bands. We denote innes states with index "n" asnd outer states with index "l". So, .nn and .ll return a square matrix (which may be 1x1 for a single band) and .ln and .nl return rectangular matrices. The important property that needs to be sattisfied is that these matrices transform covariantly under unitary transformations that mix states only inside "inner"  or "outer" spaces, but not mixing between states.

**Comment by jaemolihm** [comment]
Regarding the SHC branch, it seems that one needs some fixes to merge. I have some questions.

1. Should the definition of the spin current matrix go to `covariant_formulak.py`, not `data_K.py`?

2. Are objects re-calculated every time? For example, `frml.Omega` is used in various quantities. Is it recalculated, or is it stored somewhere?
