### ISSUE TITLE
Tabulate method with large NK

### ISSUE THREAD

**Issue by minkyu-p** [wannier-berri/wannier-berri#95]
I have observed that the tabulate method with large NK, often takes much longer than the integrate method with same NK. 
I guess this is because only one core is used after the evaluation. 

For example, if I tabulate Berry curvature of bcc Fe with NK=300 and 16 cores, the computation time reported is
```
Totally processed 288 K-points 
settinng the grid
time for setting the grid           : 0.0006632804870605469
setting new kpoints
time for setting new kpoints        : 30.688863039016724
finding equivalent kpoints
time for finding equivalent kpoints : 928.395087480545
collecting
collecting: to_grid  : 614.088725566864
collecting: TABresult  : 1.9258801937103271
collecting - OK : 616.014698266983 (9.250640869140625e-05)
Tabulating finished successfully
Time     : Total : 3960.937801361084 s
        evaluate : 2373.813616037369 s

         to_grid : 1587.1240820884705 s
         txt     : 0 s
         write   : 0 s
```
Apart from evaluation, most of the time is used in "finding equivalent kpoints" in `to_grid` method: 
https://github.com/wannier-berri/wannier-berri/blob/bdd23820d56387c743aca96e68a13025f7e404c0/wannierberri/__tabulate.py#L180-L209

So I have been trying to parallelize it under `ray`. But my attempt 
```
        @ray.remote
        def find_equiv_kpts(kpts):
            for ik,k in enumerate(kpts):
                k1=k*grid
                ik1=np.array(k1.round(),dtype=int)
                if np.linalg.norm(ik1/grid-k)<1e-5 :
                    ik1=ik1%grid
                    ik2=ik1[2]+grid[2]*(ik1[1] + grid[1]*ik1[0])
	            k_map[ik2].append(ik)
                else:
	            print ("WARNING: k-point {}={} is skipped".format(ik,k))

	kpts_id = ray.put(self.kpoints)
        ray.get( find_equiv_kpts.remote(kpts_id) )
```
is not working because `k_map` is not updated, so ZeroDivisionError occurs in the later part. I think my current knowledge and experience are not enough to do this job. 

So here I kindly ask your help. 
How can I speed up tabulate method for large NK?

Best regards,
Minkyu

**Comment by jaemolihm** [comment]
Hi Minkyu @minkyu-p , Thank you for reporting this issue.

Could you try the following change: https://github.com/wannier-berri/wannier-berri/commit/15a9d29271f75e467de0b9a77af439fed5e9e467

In this commit, I optimized that part of the function. In my test calculation, I found that "finding equivalent kpoints" took 2.2 sec before the fix, and 0.1 sec after the fix. If you confirm that this change solves the issue, I'll make a PR.

Thanks,
Jae-Mo

**Comment by minkyu-p** [comment]
Hi @jaemolihm , thank you for the effort. 

I just tested the code you changed, and it gives incredibly good performance. Here is my result with same number of cores but on different node.
```
Totally processed 288 K-points 
setting the grid
time for setting the grid           : 0.0004050731658935547
setting new kpoints
time for setting new kpoints        : 0.41611742973327637
finding equivalent kpoints
time for finding equivalent kpoints : 29.602956771850586
collecting
collecting: to_grid  : 261.97767972946167
collecting: TABresult  : 0.7980024814605713
collecting - OK : 262.77574157714844 (5.936622619628906e-05)
Tabulating finished successfully
Time     : Total : 1407.5362284183502 s
        evaluate : 1109.1500566005707 s

         to_grid : 298.3861379623413 s
         txt     : 0 s
         write   : 0 s
```

Previously, `to_grid` occupies 40% of the total execution time, but now it is 21% which becomes a half. 

Thank you for your effort again.
Minkyu

**Comment by stepan-tsirkin** [comment]
Thank you for the effort, @jaemolihm ,
After your optimization, is the bottleneck now in `self.results[r].to_grid(k_map)` ?

**Comment by jaemolihm** [comment]
> After your optimization, is the bottleneck now in `self.results[r].to_grid(k_map)` ?

Yes.
