### ISSUE TITLE
Code formatting, static code analysis

### ISSUE THREAD

**Issue by jaemolihm** [wannier-berri/wannier-berri#96]
I suggest to use python auto formatter `yapf` to unify the code style, and include `flake8` which checks the code style and programming errors to the CI.

I tried yapf (https://github.com/google/yapf) to automatically format `__kubo.py` and `fermiocean.py` (you can do this by `pip install yapf; yapf -i fermiocean.py`). See https://github.com/wannier-berri/wannier-berri/compare/master...jaemolihm:yapf for changes. It uses the PEP8 style guide https://www.python.org/dev/peps/pep-0008/ by default.
If you think they are good, we can 1) run yapf to the current codes, and 2) add yapf to the git pre-commit hook so that it formats the changes before each commit.
If there is some style that you don't like, maybe it's possible to disable that in the formatter.

`Flake8` can be used to check whether the code is following the style guide. Also, by including `flake8` to the CI, we can find some trivial errors in the PR, such as variables that are not used or undefined. For example, `flake8` gives following comments about `__kubo.py` and `fermiocean.py` (after running yapf):
```linux
jmlihm@DESKTOP-KGFE372:~/program/wannier-berri/wannierberri$ flake8 __kubo.py
__kubo.py:136:121: E501 line too long (147 > 120 characters)
__kubo.py:139:53: W291 trailing whitespace
__kubo.py:270:53: E502 the backslash is redundant between brackets
__kubo.py:271:25: E124 closing bracket does not match visual indentation
__kubo.py:291:13: F841 local variable 'fs' is assigned to but never used

jmlihm@DESKTOP-KGFE372:~/program/wannier-berri/wannierberri$ flake8 fermiocean.py
fermiocean.py:25:121: E501 line too long (141 > 120 characters)
fermiocean.py:26:121: E501 line too long (158 > 120 characters)
fermiocean.py:67:121: E501 line too long (133 > 120 characters)
fermiocean.py:257:51: W291 trailing whitespace
fermiocean.py:288:39: W291 trailing whitespace
fermiocean.py:289:57: W291 trailing whitespace
```
(I took the `.flake8` file from pyscf https://github.com/pyscf/pyscf/blob/master/.flake8. It tells flake8 to ignore or modify some style conventions. For example, the max line length can be increased.)

(The trailing whitespace errors are there because yapf does not format docstrings.)

**Comment by stepan-tsirkin** [comment]
Yes, that will be a good thing, it makes the code more readable 

Maybe I did not like only the following two cases: 

![Screenshot from 2021-11-20 18-52-58](https://user-images.githubusercontent.com/22172977/142736429-993bb993-9647-4945-8148-7f6818404f53.png)
![Screenshot from 2021-11-20 18-52-51](https://user-images.githubusercontent.com/22172977/142736430-3b6c6165-74d8-4b28-83f8-4d171b2d16db.png)
 
Generally, if a comment is long, it is better to put it before a line. But that can be fixed manually. 

Yes, and `flake8` may be useful. 

Looking forward to your PR (or split it to several PRs if possible/useful)

I guess it is important that between your run of yapf on the code and 
merging the PR we do not merge any other modifications, to avoid problems, right?

**Comment by jaemolihm** [comment]
> merging the PR we do not merge any other modifications, to avoid problems, right?

Sorry, I forgot to reply. Yes, it will be good to do so.
