### ISSUE TITLE
Issues in Path class

### ISSUE THREAD

**Issue by jaemolihm** [wannier-berri/wannier-berri#99]
One is fixed in #82.

There are other issues, which I will describe here later.

**Comment by stepan-tsirkin** [comment]
Is the other one related to #104 ? Or is there another problem?

**Comment by jaemolihm** [comment]
Sorry for the delay. No, it's another problem.

The problem is that the intermediate nodes are duplicated (` [0.5   0.5   0.5  ]` occurs twice). I'm not sure this is a bug or a feature, though.

Code:
```python3
import os
import wannierberri as wb
import pythtb as ptb
import numpy as np

def HaldanePTB(delta,t1,hop2,phi):
    lat=[[1.0,0.0],[0.5,np.sqrt(3.0)/2.0]]
    orb=[[1./3.,1./3.],[2./3.,2./3.]]
    haldane=ptb.tb_model(2,2,lat,orb)
    haldane.set_onsite([-delta,delta])
    haldane.set_hop(t1, 0, 1, [ 0, 0])

    return haldane


haldane = HaldanePTB(2,1,1/3,np.pi/10)
syst=wb.System_PythTB(haldane,berry=True,morb=True)

k_nodes = [[0.0, 0.0, 0.0], [0.5, 0.5, 0.5], [0.0, 0.0, 0.5]]
pp = wb.Path(syst, k_nodes=k_nodes, nk=5)
print(pp.labels)
print(pp.K_list)
```

Output: 
```
[jmlim@im0 wannier-berri]$ python3 a.py 
R=0 found at position(s) [[0]]
[]
NOT using ws_dist
Number of wannier functions: 2
Number of R points: 1
Recommended size of FFT grid [1 1 1]
Reading the system from PythTB finished successfully
{0: '1', 4: '2', 5: '2', 9: '3'}
[[0.    0.    0.   ]
 [0.125 0.125 0.125]
 [0.25  0.25  0.25 ]
 [0.375 0.375 0.375]
 [0.5   0.5   0.5  ]
 [0.5   0.5   0.5  ]
 [0.375 0.375 0.5  ]
 [0.25  0.25  0.5  ]
 [0.125 0.125 0.5  ]
 [0.    0.    0.5  ]]
```

**Comment by stepan-tsirkin** [comment]
Well, it does not hurt much, so it is not a bug.  but it does not help much either, so it is not a feature. 

If you have time, you may correct it. To exclude repeating points.

**Comment by jaemolihm** [comment]
Also, I have a question. What is the standard way to calculate/plot a quantity along a given k path?

**Comment by stepan-tsirkin** [comment]
> Also, I have a question. What is the standard way to calculate (and plot, if possible) a quantity along a given k path? Direct tabulation using the path object did not work.

Actually it is meant to use a `Path` instead of `Grid` in the `tabulate()` function. 
Do these [examples](https://wannier-berri.org/exampleFe.html#plotting-along-lines) not work? what is the error?

**Comment by jaemolihm** [comment]
The error was #104 😃

**Comment by AbhirupRK** [comment]
> I found that the error is fixed with #104 smiley

I'm having the same problem. Currently using version 0.11.0. Can you please guide me on how to solve this problem?

**Comment by jaemolihm** [comment]
Hi @AbhirupRK , the fix is not yet released, nor included in the develop branch.
Currently, you can solve the problem by cloning the branch in #104. (Clone this repository and git checkout origin/fix_tabulate_path and then install.)
Alternatively, you can wait until the fix is merged and released.

**Comment by AbhirupRK** [comment]
Thanks a lot for the reply.
